### ISSUE TITLE
KeyError exception

### ISSUE THREAD

**Issue by txellgb** [bitextor/bitextor#102]
**Description**
KeyError exception is raised in features/bitextor-structuredispance.py, line 117 

The exception happens when the condition in line 65, in the `extract_structure_representations `method, is not matched. Hence, the `documents` dictionary does not have a key (`fileid`) for all the documents. 
Line 117 does not check if the key exists before trying to access it, so it crashes. 

**Workaround**
I have fixed the issue by addind an space as a document structure for fileids that are empty, in the finally block:

            finally:
                if not fileid in docs:
                    docs[fileid] = " "
                fileid += 1

This is just a workaround, I'm not sure about the implications of this.

**Comment by lpla** [comment]
I made a commit with a similar fix. We still need to do a proper fix for this error cases (a non XML/HTML file as input), but meanwhile, this should, at least, not crash.

**Comment by lpla** [comment]
Please, check latest commit to see if it doesn't crashes when both empty document is in target. I forgot that if document is completely empty it could crash calculating length ratio.

If all works for you, please close this issue.

**Comment by txellgb** [comment]
It works. Thanks a lot.
