### ISSUE TITLE
Remove `sync' from beginning of each job

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#106]
Why are we running sync at the beginning of a job?  Combined with there being entirely too many small jobs means sync is run a lot.  And some jobs use sort with temporary files on disk, which are being unnecessarily sync by other jobs starting in parallel.

**Comment by mespla** [comment]
We added this because in some clusters we  were having synchronization problems over the file system: files written by a job on a node on the shared file system were unavailable for another job on a different node. One thing we could do is to make this optional.

**Comment by kpu** [comment]
You can sync a specific filesystem or file.  Also, does sync at the beginning help with some filesystems?  Seems the intended semantics was to sync a file at job end before close (or by name after close).

**Comment by lpla** [comment]
After the latest Snakefile rewrite for Bitextor 8.0, syncs are gone. Closing.
