### ISSUE TITLE
Floating-point comparison issues are resulting in duplicated lines

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#108]
For deduplication, we are sorting by bicleaner score then by source and target:
https://github.com/bitextor/bitextor/blob/master/snakemake/Snakefile#L417
The problem is that apparently bicleaner is slightly non-deterministic with floating-point operations, so the final values can be slightly off in score.  
```
medjugorjeweb.com/comm/sb0998pl.htm     medjugorjeweb.org/comm/sb0998ge.htm     Życie wieczne to nie jest coś nad chmurami, coś niejasnego, ale przeciwnie – jest to rzeczywista wspólnota tych, którzy kochają.        Ewiges Leben ist nicht etwas oben hinter diesen Wolken, etwas unklares, sondern vielmehr ist es eine wirkliche Gemeinschaft von denen die wir lieben.   0.42025 0.9696954785648678      0.8590604026845637      2023
medugorje.org/comm/sb0998pl.htm medugorje.org/comm/sb0998ge.htm Życie wieczne to nie jest coś nad chmurami, coś niejasnego, ale przeciwnie – jest to rzeczywista wspólnota tych, którzy kochają.        Ewiges Leben ist nicht etwas oben hinter diesen Wolken, etwas unklares, sondern vielmehr ist es eine wirkliche Gemeinschaft von denen die wir lieben.   0.42025 0.9696954785648677      0.8590604026845637      20      23
```
Then these sentences get leaked as duplicates into the "deduped" TMX.  

Bicleaner is not exactly the fastest tool, so I think we should be deduplicating before bicleaner (like we do for MT), which would resolve the issue and increase speed.  

Found by @kirefu.

**Comment by mbanon** [comment]
Hi @kpu ,
we are aware of that since the last release (I think it was mentioned at some point on the mailing list).
We proposed to use less decimal places (for example, 3 instead of the current 16).

The current order is bicleaner > filtering by threshold > dedup > tmx.

The downside of dedupping before bicleaning is that it will require sorting & dedupping really huge files (I'm thinking on the German/French/Spanish raw files, for example). So, even having to biclean less data, I am not sure if the massive amount of time/space required for sorting will be worth.

**Comment by kpu** [comment]
I've deduped 1.8 trillion lines to 900 billion over 4 years ago.  https://github.com/kpu/preprocess has an in-memory based hash table deduper optimized for speed and somewhat RAM.  For the bigger jobs (when that runs out of RAM), we shard by the hash of the sentence pair first.  The sharder is also in there.  

While we probably don't need 16 decimal places, having fewer does not inherently solve the problem, just possibly lessen the frequency.

**Comment by mbanon** [comment]
Ok then.

We will change Bicleaner to user fewer decimal places anyway.

**Comment by mbanon** [comment]
I'm dropping here a copy of what I proposed in the Paracrawl mailing list:

> Hey all,
> after today's meeting, here is a proposal for dedupping keeping the URLs.
> 
> As we mentioned, we are developing a BiFixer tool that will include features from the deprecated-to-be restorative-cleaning (fix spelling and mojibake issues, ...) as well as new features such as fixing segmentation issues. This new tool should be run before Bicleaner, so our plan is to cover corpus deduplication into this tool as well (as proposed by Ken).
> 
> This is how we propose to proceed:
> 
> 0. Run Bitextor stuff as usual.
> 1. When running Bifixer (in Bitextor pipeline, in the place currently occupied with clean-restorative.sh), besides fixing issues in the sentences, it obtains the hash for each parallel sentence. This hash, together with the source and target URLs, is stored into a RAM-friendly dictionary object (for example, Redis with persistance, or discoDB, or any other solution). When an already existing hash is found, the URLs are appended to the previously existing ones.
> 2. After running Bifixer, two files are produced: one deduplicated file with the corpus in the format source-target-hash-extracolumns, and the other one with hash-url1-url2-...-urln.
> 3. Run bicleaner on the deduplicated file.
> 4. Run any other tool needed.
> 5. TMX building: The current script (bitextor-buildTMX-dedup.py) has to be modified to build TMX from the deduplicated file, but obtaining all the URLs from the hashes-URLs file (again, loading it with the same RAM-friendly tool).
> 
> An extra advantage of this method is that it allows to build incremental corpora, keeping them duplicates-free even if they were processed with different versions of Bicleaner: we just need to sort by hash instead of by Bicleaner score before dedupping.

**Comment by mbanon** [comment]
Changed to 3 decimal places in Bicleaner 0.12

**Comment by kpu** [comment]
Reducing decimal places does not solve the problem, only reduce the frequency with which it occurs, as we discussed.  However, a different pipeline to deduping does.

**Comment by lpla** [comment]
This is related to https://github.com/bitextor/bitextor/issues/117#issuecomment-522526950

Once #117 is fixed, this issue should be automatically fixed, given that we will use `cache`.

**Comment by mbanon** [comment]
> Reducing decimal places does not solve the problem, only reduce the frequency with which it occurs, as we discussed. However, a different pipeline to deduping does.

I thought it was ok to close this issue, since there is a different issue for that (#117, as @lpla noted)

**Comment by kpu** [comment]
You can close this in favor of #117.  I was reacting to closing this issue with a statement that 3 decimal places solved it.
