### ISSUE TITLE
Language that doesn't have an ISO 639-1 code?

### ISSUE THREAD

**Issue by popstick** [bitextor/bitextor#109]
Is it possible to run Bitextor for a language that doesn't have a ISO 639-1 code? I tried creating a nonbreaking_prefix file for Moses and Bicleaner but still end up with empty files. I'm guessing the language needs to be identified with langid.py?

**Comment by lpla** [comment]
Well, Bitextor runs with a language pair. Which pair are you using? We need to detect languages to obtain documents in those two languages only and classify them in two groups to compare. It could be possible to modify Bitextor to use the "unknown" detected documents as the non ISO-639-1 language, but the other one needs to be well detected.

**Comment by popstick** [comment]
That seems like a good solution. The language pair is English and Tetun so I imagine it could work. Thanks for the response.

**Comment by lpla** [comment]
I don't think I even need to modify code for that. If you created a nonbreaking_prefix and Bicleaner model, which language code used for them? `cld2` (which is the language detector we use in `bitextor`) uses `un` code for unknown languages. It is likely that if you use that one for all resources, it should work (although, some dirty text could be also included, as it is detected as unknown too).

**Comment by popstick** [comment]
Excellent. Using the un code worked very well. Thanks for the tip!

**Comment by popstick** [comment]
Just one more thing, I keep getting the following error when using wget. It seems to be looking for output.warc but only output.warc.gz exists. Any ideas?


hostname=naroman
Starting...
Executing:wget --mirror  -A "pdf" -q http://bafuturu.org -P /home/naroman/bitextor/transient-default-wget-en-un/downloaded.bafuturu.org.DPKvPq  --warc-file "/home/naroman/bitextor/transient-default-wget-en-un/downloaded.bafuturu.org.DPKvPq/output" 
WARC output does not work with timestamping, timestamping will be disabled.
Finished!
	Command being timed: "nice ionice -c 3 ./bitextor-wget.py --url http://bafuturu.org --output-path /home/naroman/bitextor/transient-default-wget-en-un/downloaded.bafuturu.org.DPKvPq -f pdf --warc /home/naroman/bitextor/transient-default-wget-en-un/downloaded.bafuturu.org.DPKvPq/output"
	User time (seconds): 5.46
	System time (seconds): 1.10
	Percent of CPU this job got: 8%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:15.40
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 21668
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 19181
	Voluntary context switches: 6051
	Involuntary context switches: 75
	Swaps: 0
	File system inputs: 0
	File system outputs: 713896
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
cat: /home/naroman/bitextor/transient-default-wget-en-un/downloaded.bafuturu.org.DPKvPq/output.warc: No such file or directory
[Thu Jul  4 03:45:02 2019]
Error in rule wget_download:
    jobid: 16
    output: /home/naroman/bitextor/permanent/bitextor-output-default-wget-en-un/warc/bafuturu.org/wget.warc.xz

RuleException:
CalledProcessError in line 1002 of /home/naroman/bitextor/snakemake/Snakefile:
Command 'set -euo pipefail;  echo hostname=$HOSTNAME; DIRNAME=$(mktemp -d "/home/naroman/bitextor/transient-default-wget-en-un/downloaded.bafuturu.org.XXXXXX"); WGETWARCPATH=$DIRNAME/output;/usr/bin/time -v nice ionice -c 3 ./bitextor-wget.py --url http://bafuturu.org --output-path "$DIRNAME"   -f pdf  --warc $WGETWARCPATH; cat $WGETWARCPATH.warc | nice ionice -c 3 xz -c -T 0 > /home/naroman/bitextor/permanent/bitextor-output-default-wget-en-un/warc/bafuturu.org/wget.warc.xz;rm -rf $DIRNAME;' returned non-zero exit status 1
  File "/home/naroman/bitextor/snakemake/Snakefile", line 1002, in __rule_wget_download
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job wget_download since they might be corrupted:
/home/naroman/bitextor/permanent/bitextor-output-default-wget-en-un/warc/bafuturu.org/wget.warc.xz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/naroman/bitextor/.snakemake/log/2019-07-04T034346.255943.snakemake.log

**Comment by lpla** [comment]
Hi. Could you please test with latest commit in master? I don't know why it is compressing that WARC and not mine in tests. I forced now with "--no-warc-compression". Please, let me know if that fixes your issue.

**Comment by popstick** [comment]
The change didn't seem to come through in the commit but I added it myself to bitextor-wget.py and it worked well. Thanks again.

Having some trouble with pdftohtml now but will play with it and see what I can find out.

**Comment by popstick** [comment]
Fixed my PDF issues by 'adding pdf-converter: pdf-extract' to snakemake file.

**Comment by lpla** [comment]
In case you want to use default pdf converter from `poppler` library, install `poppler-utils` package (with `apt` if using a Debian based system): `sudo apt install poppler-utils`

Please don't hesitate to report and open new issues.

Thanks!

**Comment by popstick** [comment]
> I don't think I even need to modify code for that. If you created a nonbreaking_prefix and Bicleaner model, which language code used for them? `cld2` (which is the language detector we use in `bitextor`) uses `un` code for unknown languages. It is likely that if you use that one for all resources, it should work (although, some dirty text could be also included, as it is detected as unknown too).

This used to work well but doesn't seem to work anymore in the new releases. Could something have changed?

Getting this error:
WARNING: no 'un' data found in jsmp. Creating empty files instead

The language pair is English (en) and Tetun (un). There's definitely data there, but only English is working.

Have tried with both cld2 and cld3. Same result.

Any ideas?

**Comment by popstick** [comment]
OK, I found the difference. 

In bitextor-warc2preprocess.py :

if lang == "un":
        logging.info("Language of document " + url + " could not be identified")
        continue 

I'll try disabling this and report back.

**Comment by mbanon** [comment]
Hi @popstick ,
as for Bicleaner, we added the "--disable_lang_ident" flag in version 0.12 (current master branch), that prevents Bicleaner to use any  rule that relies in language identification.
(see https://github.com/bitextor/bicleaner/blob/master/CHANGELOG.md )

In Bicleaner 0.13 we are going a little beyond and allow training with that option, and avoid using any feature using language identification. This version is not officially released yet, but you can find it in a branch (that is quite stable now so it should be safe to use)
(see https://github.com/bitextor/bicleaner/blob/bicleaner-0.13/CHANGELOG.md)

I hope you find these options useful!

**Comment by lpla** [comment]
@popstick 

Tetun language is not supported by `cld2` or `cld3`, and the code 'un' is used by `cld2` to mark text as an "unknown" language.

**Comment by popstick** [comment]
I commented out that line and it works well.

@lpla 
Yes, exactly. I don't think Tetun will ever be supported but 'un' works fine when paired with English.

@mbanon 
Good to know, thanks! I haven't managed to get Bicleaner working yet but I will persist.

**Comment by lpla** [comment]
Well, you will get some noise, however. You now don't filter Tetun text detected as 'un' by `cld2`, yes, but also you are introducing everything else that is detected as unknown, like badly formatted/detected text, non-supported language texts and, in general, more noise.

Just keep that in mind.
