### ISSUE TITLE
NFKC unicode normalisation

### ISSUE THREAD

**Issue by wwaites** [bitextor/bitextor#111]
- Are we normalising unicode?
- Are we transforming HTML-style `&123;` characters to the equivalent unicode?

**Comment by lpla** [comment]
`ftfy` normalises unicode (https://github.com/bitextor/bitextor/blob/f3159993fe70971906ca527c53467f396b28466f/bitextor-warc2preprocess.py#L195) and BeautifulSoup transforms HTML entities (https://github.com/bitextor/bitextor/blob/f3159993fe70971906ca527c53467f396b28466f/bitextor-warc2preprocess.py#L245)

**Comment by wwaites** [comment]
Excellent, thank you! Just checking, this was a question when reviewing today.
