### ISSUE TITLE
warc2preprocess doesn't check that input is text

### ISSUE THREAD

**Issue by wwaites** [bitextor/bitextor#112]
Internet Archive WARC files contain:
- DNS responses that are not HTTP responses and do not contain useful text
- JavaScript and CSS that do not contain useful text
- PNG, JPG and GIF images that do not contain useful text
- Lots of other stuff that does not contain useful text
These should be filtered out.

**Comment by lpla** [comment]
All these filters are implemented in https://github.com/bitextor/bitextor/commit/1cf9f0e5049f08561f75d3136b9f88303145c898

If you find any other issue regarding WARC record formats, please, reopen this issue.

Thank you!
