### ISSUE TITLE
Optimized bicleaner pipeline

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#117]
Here's a pipeline for bicleaning.  

The `cache` program from https://github.com/kpu/preprocess/ wraps another command line program by caching the result from identical input lines with an in-memory hash table.  So we wrap cache around bicleaner to avoid scoring identical sentence pairs; this also solves the problem with slight non-determinism coming out of bicleaner.  And use GNU parallel to parallelize bicleaner over the entire node.  Bicleaner is modified to read only a sentence pair and write only the score.  

URLs and sentence pairs are currently rejoined using `paste` but I am planning to modify `cache` so it can also carry information with each line.  This will eliminate the ugly double-read and paste.  

If the raw data is too big for the aforementioned in-memory hash table, we first shard by sentence pair using the `shard` program from https://github.com/kpu/preprocess/ to break it into machine-sized pieces.    The `shard` program ensures that identical lines end up in the same shard.  

Data is shorted within each shard so that the shards can be merged together into one TMX sorted by score (using `LC_ALL=C sort -m -t $'\t' -k5,5rg -k3,4 -k1,2`).  

By design, we avoid doing a lot of little steps that would create unnecessary compression/decompression and disk read/write.  

To note, it applies awk to get columns back in the order that the releases have.  

```bash
#!/bin/bash
set -e -o pipefail
l=$1
if [ $# != 1 ]; then
  echo Usage: $0 language 1>&2
  exit 1
fi
export PATH=$PATH:/fs/meili0/faheem/miniconda3/bin
source activate bitextor
raw=/fs/elli0/s0565741/experiment/paracrawl/v3/${l}-en/permanent/${l}-en.raw.xz
echo "About to run"
paste \
    <(pv "$raw" |xzcat |awk -F '\t' '{ print $2"\t"$1"\t"$4"\t"$3 }') \
    <(xzcat "$raw" |awk -F '\t' '{ print $4"\t"$3 }' |/fs/magni0/heafield/preprocess/build/bin/cache parallel -k --pipe /fs/meili0/faheem/bitextor.malign/bicleaner/bicleaner/bicleaner_classifier_lite_score_only.py -q --threshold 0.7 - /home/s0565741/workspace/experiment/paracrawl/v3/bicleaner_models/en-${l}/training.en-${l}.yaml) \
  | tee >(pigz >hieu.$l.raw.gz) \
  | awk -F '\t' '{ if ($5 >= 0.7) { print } }' \
  | /fs/meili0/faheem/bitextor.malign/bitextor-elrc-filtering.py -c "url1,url2,seg1,seg2,bicleaner" -s \
  | LC_ALL=C sort -t $'\t' -k5,5rg -k3,4 -k1,2 --parallel=$(nproc) \
  | pigz > hieu.$l.sorted.gz
```

**Comment by mbanon** [comment]
Hi Ken,
as I mentioned few weeks ago, we are working in  Bifixer*, a tool that will replace restorative-cleaning. This Bifixer fixes issues in text (as the old restorative-cleaning does), and does some other jobs, such as deduplicating (storing hashes + urls in an external file) by using Redis. 
So, at the point that Bicleaner is run in the pipeline, there should be no duplicates in the corpus.
*It's not in GitHub yet, but I can upload it right now if you want

**Comment by kpu** [comment]
With regard to fixing issues within a sentence pair, that's fine, we can easily change the above to treat the fixed sentence as part of the value and only carry the URLs alongside.  
With regard to deduplication, benchmark the dedupe program from https://github.com/kpu/preprocess/ .  I am having trouble believing that a network-based program can compete with this.  Redis might have other uses in ParaCrawl, but I don't think deduplication is going to be efficient.

**Comment by mbanon** [comment]
Ok.  We are doing some benchmarking.

**Comment by lpla** [comment]
We are trying to use `cache` with the `master` branch pipeline but we are having some issues. Right now, `bifixer` is giving a hash (second-to-last column) for detected duplicates and near duplicates. Example from @mbanon (file `example.en-es.bifixer`):

```
http://bible-library.com/?bookid=26&chapter=46&translation=kjv	http://bible-library.com/?bookid=26&chapter=46&translation=3	14And thou shalt prepare a meat offering for it every morning, the sixth part of an ephah , and the third part of an hin of oil , to temper with the fine flour ; a meat offering continually by a perpetual ordinance unto the LORD .	14Y con él harás todas las mañanas presente de la sexta parte de un epha, y la tercera parte de un hin de aceite para mezclar con la flor de harina: presente para Jehová continuamente por estatuto perpetuo.	000389cb8f6fe8e8	92.07
http://www.godrules.net/library/douay/douayeze46.htm	http://www.godrules.net/library/SAmerican/valera/valeraeze46.htm	14 And he shall offer the sacrifice for it morning by morning, the sixth part of ephi: and the third part of a bin of oil be mingled with the fine hour: a to the Lord by ordinance continual and everlasting.	46:14 Y con él harás todas las mañanas presente de la sexta parte de un epha, y la tercera parte de un hin de aceite para mezclar con la flor de harina: presente para Jehová continuamente por estatuto perpetuo.	000389cb8f6fe8e8	92.08
http://wordpocket.com/kj/26/46.htm	http://wordpocket.com/sp/26/46.htm	14 And thou shalt prepare a meat offering for it every morning, the sixth part of an ephah, and the third part of an hin of oil, to temper with the fine flour; a meat offering continually by a perpetual ordinance unto the LORD.	14 Y con él harás todas las mañanas presente de la sexta parte de un epha, y la tercera parte de un hin de aceite para mezclar con la flor de harina: presente para Jehová continuamente por estatuto perpetuo.	000389cb8f6fe8e8	92.34
http://bible-server.org/Bible.php?L2=&translation=KJV&book=Ezekiel&ch=46	http://bible-server.org/Bible.php?L2=&translation=SPA&book=Ezekiel&ch=46	14 And thou shalt prepare a meat offering for it every morning, the sixth part of an ephah, and the third part of an hin of oil, to temper with the fine flour; a meat offering continually by a perpetual ordinance unto the LORD.	14 Y con él harás todas las mañanas presente de la sexta parte de un epha, y la tercera parte de un hin de aceite para mezclar con la flor de harina:presente para Jehová continuamente por estatuto perpetuo.	000389cb8f6fe8e8	92.48
www.biblegematria.com/kjv-ezek2.html	www.biblegematria.com/spezeq2.html	And thou shalt prepare a meat offering for it every morning, the sixth part of an ephah, and the third part of an hin of oil, to temper with the fine flour; a meat offering continually by a perpetual ordinance unto the LORD.	Y con él harás todas las mañanas presente de la sexta parte de un epha, y la tercera parte de un hin de aceite para mezclar con la flor de harina: presente para Jehová continuamente por estatuto perpetuo.	000389cb8f6fe8e8	93.02
```

We expect to use this hash with `cache` as the "cache field", so, after sorting numerically and reversed using last column we want to only execute `bicleaner` with the sentence with highest score (93.02 in our example), given a hash (000389cb8f6fe8e8 for us). Something like this (adding a -k/--key option in `cache`):

`cat example.en-es.bifixer | LC_ALL=C sort -k6nr -t "	" | preprocess/bin/cache --key 5 parallel -k --pipe bicleaner/bicleaner/bicleaner_classifier_lite.py .....`

@kpu is this viable?

**Comment by lpla** [comment]
Implemented in Bitextor 'cache_and_dedup' dev branch (98f50d51ee66e04500d66b206bc71490a55fbdd6) using kpu/preprocess fork (pull request: https://github.com/kpu/preprocess/pull/8).
