### ISSUE TITLE
myconfig.yaml example file options are outdated

### ISSUE THREAD

**Issue by xnlp** [bitextor/bitextor#118]
**Describe the bug**
When the comand " ./bitextor.sh -s myconfig.yaml -j 4" is executed, there is an error ocurring:
SystemExit in line 207 of /home2/zjx/tools/mt/bitextor/snakemake/Snakefile:
None
  File "/home2/zjx/tools/mt/bitextor/snakemake/Snakefile", line 211, in <module>
  File "/home2/zjx/tools/mt/bitextor/snakemake/Snakefile", line 207, in ValidateArgs
  File "/home2/zjx/.pyenv/versions/3.5.2/lib/python3.5/_sitebuiltins.py", line 26, in __call__

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lpla** [comment]
Hi. Could you please post your `myconfig.yaml` content? I can't debug this properly without the config used.

**Comment by xnlp** [comment]
1 # BITEXTOR CONFIG FILE
  2 
  3 # GENERAL OPTIONS
  4 ##Directory where Bitextor is installed
  5 bitextor: /home2/zjx/tools/mt/bitextor
  6 ##Folders used during processing: temp is the temporal folder (/tmp by default); permanentDir will contain the results of crawling: the parallel corpus built and the WARC files obtained through crawling; tra    nsientDir will contain the rest of files generated during processing
  7 temp: /home2/zjx/tools/mt/bitextor/transient
  8 permanentDir: /home2/zjx/tools/mt/bitextor/bitextor-output
  9 transientDir: /home2/zjx/tools/mt/bitextor/transient
 10 ##Segment spliters and word tokenizers
 11 LANG1Tokenizer: /home2/zjx/tools/mt/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l en
 12 LANG2Tokenizer: /home2/zjx/tools/mt/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l fr
 13 LANG1SentenceSplitter: /home2/zjx/tools/mt/bitextor/preprocess/moses/ems/support/split-sentences.perl -q -b -l en
 14 LANG2SentenceSplitter: /home2/zjx/tools/mt/bitextor/preprocess/moses/ems/support/split-sentences.perl -q -b -l fr
 15 ##Languages for which parallel data is crawled; note that if MT is used in the pipeline (either for alignment or evaluation) the translation direction used will be lang1 -> lang2
 16 lang1: en
 17 lang2: fr
 18 
 19 
 20 # CRAWLING OPTIONS
 21 ##HTTrack activation: if it is not activated, Creepy crawler is used
 22 httrack: true
 23 ##Crawling sources: either a list of domains (without http/https) or a langstat file
 24 hosts: ["www.elenacaffe1863.com","vade-retro.fr"]
 25 langstat: /home2/zjx/tools/mt/bitextor/langstat/langstats.all.gz
 26 langstatThreshold: 50000000
 27 langstatExcludeDomains: /home2/zjx/tools/mt/bitextor/snakemake/exclude-hosts
 28 # CREEPY CRAWLER SPECIFIC OPTIONS ##
 29 ##Crawling time limit in seconds (s)
 30 crawlTimeLimit: 30s
 31 ##If this option is enabled the crawler will keep crawling across a whole top-level domain (.es, .com, .fr, etc.)
 32 crawlTld: false
 33 ##Crawling size limit
 34 crawlSizeLimit: 1G
 35 ##Number of threads used by the Creepy crawler
 36 crawlerNumThreads: 1
 37 ##Connection timeout limit (Default 10 seconds)
 38 crawlerConnectionTimeout: 10
 39 
 40 
 41 # DICTIONARIES
 42 dic: /home2/zjx/tools/mt/bitextor/en-fr.dic
 43 ##Corpus for bilingual dictionaries and-or SMT/NMT training, if dictionary or models not given, respectively.
 44 initCorpusTrainPrefix: ""
 45 #Corpus for SMT training
 46 initCorpusDevPrefix: ""
 47 initCorpusTestPrefix: ""
 48 ##If enabled, boilerpipe is filtered from HTML's
 49 boilerpipeCleaning: true
 50 
 51 
 52 # DOCUMENT ALIGNMENT
 53 ##Which document aligner to use:
"myconfig.yaml" 100L, 5015C                                                                                                                                                                      1,1           Top

**Comment by xnlp** [comment]
the attach file is listed as follows:
[myconfig.zip](https://github.com/bitextor/bitextor/files/3399691/myconfig.zip)

**Comment by lpla** [comment]
Please, check all output. I reproduced the issue but I had more output than the one you reported:
```
Starting bitextor
Validation error. Stopping. {'bicleanerCorpusTrainingPrefix': ['must be of list type'], 'initCorpusDevPrefix': ['must be of list type'], 'initCorpusTestPrefix': ['must be of list type'], 'initCorpusTrainPrefix': ['must be of list type'], 'langstatExcludeDomains': ['unknown field'], 'minquality': ['unknown field']}
SystemExit in line 211 of /home/lpla/permanent/bitextor/snakemake/Snakefile:
None
  File "/home/lpla/permanent/bitextor/snakemake/Snakefile", line 216, in <module>
  File "/home/lpla/permanent/bitextor/snakemake/Snakefile", line 211, in ValidateArgs
  File "/usr/lib/python3.6/_sitebuiltins.py", line 26, in __call__
```
Some options in your config file should be as a list of strings, not as a single string. Please, change that and try again.

**Comment by xnlp** [comment]
Hi,myconfig.yaml file is a copy of config.yaml in directory of snakemake,
and I only do a bit of change on the path of the file. Therefore, Could you
provide me a sample file for reference and debug?
I am looking forward to hearing from you, Thank you!

Leo <notifications@github.com> 于2019年7月26日周五 下午8:02写道：

**Comment by lpla** [comment]
You are right, this file is outdated. Please, use [`snakemake/example/tests/default.en-fr.yaml`](https://github.com/bitextor/bitextor/blob/master/snakemake/example/tests/default.en-fr.yaml) or [`snakemake/example/tests/external-mt.en-fr.yaml`](https://github.com/bitextor/bitextor/blob/master/snakemake/example/tests/external-mt.en-fr.yaml) while we fix `myconfig.yaml` example.

**Comment by xnlp** [comment]
Hi, the training.en-fr.yaml mentioned in default.en-fr.yaml or external-mt.en-fr.yaml is  not found in the bitextor projects. Could you provide the file for me ? I am looking forward to hearing from you, Thanks!

**Comment by xnlp** [comment]
I executed the command ./bitextor.sh -s myconfig.yaml -j 4
Validation error. Stopping. {'bicleanerCorpusTrainingPrefix': ['required field']}
SystemExit in line 207 of /home2/zjx/tools/mt/bitextor/snakemake/Snakefile:
None
  File "/home2/zjx/tools/mt/bitextor/snakemake/Snakefile", line 211, in <module>
  File "/home2/zjx/tools/mt/bitextor/snakemake/Snakefile", line 207, in ValidateArgs
  File "/home2/zjx/.pyenv/versions/3.5.2/lib/python3.5/_sitebuiltins.py", line 26, in __call__

**Comment by xnlp** [comment]
Hi, Thanks to you very much! Now I have another question that where are the
papers or literature related to the bitextor project?

Leo <notifications@github.com> 于2019年8月1日周四 下午4:58写道：

**Comment by xnlp** [comment]
Hi, When I use the following command "git pull origin master" or " git
fetch origin master:tmp  git diff tmp git merge tmp " to get the latest
bitextor project, there is a bug ocurring:
Updating c8704cd..38de33a
error: Updating the following directories would lose untracked files in it:
bleualign-cpp
Aborting

Could you help me with this?

Z Jx <zjxnlp@gmail.com> 于2019年8月9日周五 下午10:37写道：

**Comment by lpla** [comment]
> Hi, Thanks to you very much! Now I have another question that where are the papers or literature related to the bitextor project?

The only literature regarding the actual state of Bitextor is the README.md. There are old papers like [this](http://mt-archive.info/MTS-2009-Espla-Gomis.pdf) but they are mostly obsolete now.




> Hi, When I use the following command "git pull origin master" or " git fetch origin master:tmp git diff tmp git merge tmp " to get the latest bitextor project, there is a bug ocurring:
> Updating [c8704cd](https://github.com/bitextor/bitextor/commit/c8704cd1725661cc82ec37930f01c35ba006eb11)..[38de33a](https://github.com/bitextor/bitextor/commit/38de33ac54debbf3b2987f3474a24346262c74d3)
> error: Updating the following directories would lose untracked files in it:
> bleualign-cpp
> Aborting
> Could you help me with this?

We moved bleualign-cpp folder to an external repository. Try to [clean](https://stackoverflow.com/questions/42373656/git-pull-yields-error-updating-the-following-directories-would-lose-untracked) and reinstall the bitextor cloned repo or download it again.
