### ISSUE TITLE
How to ignore host specific rule exception.

### ISSUE THREAD

**Issue by hiropppe** [bitextor/bitextor#125]
I'm newbie to bitextor and snakemake.

I want to ignore host specific rule exception like DNS lookup error at wget_download and merge successful outputs to sents rule.

Is there a way to do this ?

I try snakemake with --keep-going option but workflow failed with message below.
> Exiting because a job execution failed. Look above for error message

**Comment by hieuhoang** [comment]
there's no way to do this.You need to exclude the host by deleting it from permanent/hosts.gz or adding it to permanent/post-crawl-exclude

**Comment by hiropppe** [comment]
thanks.
Snakemake (with --keep-going option) seems to fail after running to bicleanerfilter for all host (join point to sent rule).
Resuming from the sent rule using successful hosts as inputs might help things. 
I'll try somehow.
