### ISSUE TITLE
Sentence Spiltting

### ISSUE THREAD

**Issue by kirefu** [bitextor/bitextor#126]
**Lang2 being split incorrectly with Lang1 rules**

Whilst looking at experimental results of the trie, we've stumbled across another potential bug. Why is only SENTTOK1 fed into this program? This means that we have been using non-English rules to split all of our English sentences. An example of this adverse behavior:

_http://www.hotfe.org/ebook-files/apnx-file-extension
Probably the situation was that it had an extension not used before on your computer, e.g. APNX._

The above sentence split by using Polish rules gave:

_Probably the situation was that it had an extension not used before on your computer, e.g._ 

Both sentences splitters should be added as arguments, and extract_lett.py modified correspondingly.

**Comment by lpla** [comment]
You are right, @kirefu. This is a very old bug that came from Buck's alignment code, got into Malign and now in Bitextor. @zuny26 made a fix with your proposal. We tested it, but please, test it also with the case you identified and close the issue if it works for you.

**Comment by kirefu** [comment]
So I went to test if this was fixed, but may have inadvertently come across a different problem, which is the output of the extract_lett.py file looks very wrong, and nothing like what Hieu got.

I am testing on 'eso' domain:

```
python3 /fs/meili0/faheem/bitextor/document-aligner/utils/extract_lett.py \
-x --langs pl,en \
--plaintextfile /fs/elli0/s0565741/experiment/paracrawl/v3/pl-en/transient/eso/plain_text.xz \
--urlfile /fs/elli0/s0565741/experiment/paracrawl/v3/pl-en/transient/eso/url.xz \
--langfile /fs/elli0/s0565741/experiment/paracrawl/v3/pl-en/transient/eso/lang.xz \
--splitter1 "/home/s0565741/workspace/github/paracrawl/bitextor.malign.old/preprocess/moses/tokenizer/tokenizer.perl -l pl -a -b -q" \
--splitter2 "/home/s0565741/workspace/github/paracrawl/bitextor.malign.old/preprocess/moses/tokenizer/tokenizer.perl -l en -a -b -q" \
--prune_type "words" \
--prune 80 \
--output_dir /fs/meili0/faheem/rough/

```

It seems to be mostly outputting extremely short sentences / lists. For an example comparison -

Hieu's file from March: 

```
xzcat /fs/elli0/s0565741/experiment/paracrawl/v3/pl-en/transient/eso/docalign/en.extracted.xz | grep "www.eso.org/public/ireland/events/special-evt/50years/50highlights50years/?lang"

```

My file:

```
xzcat /fs/meili0/faheem/rough/en.extracted.xz | grep "www.eso.org/public/ireland/events/special-evt/50years/50highlights50years/?lang"

```

**Comment by lpla** [comment]
I think that your example is wrong, because `--splitter1` and `--splitter2` should be sentence splitters (split-sentences.perl, for example) and you used the Moses word tokenizer, so, that's why you are outputting "short sentences".

**Comment by kirefu** [comment]
Ah rookie mistake, sorry. Tested and looks like it works fine now.
