### ISSUE TITLE
urls.append()

### ISSUE THREAD

**Issue by kirefu** [bitextor/bitextor#131]
Hi,

https://github.com/bitextor/bitextor/blob/b30fc9aee8a999ae1de317345d3d360e03640d23/document-aligner/scorer.py#L170

Just working on the document aligner, and wondering if there is a particular but obscure reason why `url_list.append(url)` happens before the `if not counts:` statement, seeing as `url_list` is returned. I would move it after the if statement, if this is possible.

Faheem

**Comment by lpla** [comment]
HI @kirefu. Code is correct, as we want to return the same urls that are allocated in `lil_matrix`, which are all, not only the ones that have `counts`. The `if not counts:` saves us time to calculate and fill an "zero" value in an already "zero" matrix box.

**Comment by kirefu** [comment]
Why do we want to keep the urls that produce zero counts? Would we not just be calculating the cosine similarity with a vector full of zeros, so you would not expect a match?

**Comment by kirefu** [comment]
Right, I see, thanks!
