### ISSUE TITLE
deferred attribute in .yaml config file

### ISSUE THREAD

**Issue by jjmartinez-taiger** [bitextor/bitextor#132]
**Describe the bug**
deferred value in .yaml config file (bitextor) seems to be not supported. It works if commented.

**To Reproduce**
1. Go to /opt/bitextor. Use the example .yaml file included.
2. Execute bitextor.sh -s snakemake/example/tests/config.yaml
3. Scroll down if needed to see the error

**Expected behavior**
Not sure what deferred is for.

**Screenshots**
![image](https://user-images.githubusercontent.com/36634572/64376392-6e576000-d028-11e9-99c4-e152a1938eba.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser -
 - Version v7.2

**Comment by lpla** [comment]
Hello Jose. Glad to hear from you!

Which version of Bitextor are you using? Are you using latest Bitextor commit from master? I think I tested deferred crawling a few days ago before releasing Bitextor 7.2 and it worked.

Deferred is only unsupported in Bitextor 7.0 and deprecated versions (<6.0)

**Comment by jjmartinez-taiger** [comment]
Hi Leo! Nice to hear from you too!

I think that's the issue. That it's not supported but several yaml examples
still have the attribute, example
https://github.com/bitextor/bitextor/blob/master/snakemake/example/tests/config.yaml

Regards


*José J. Martinez*

*VP of Technology*
www.taiger.com
+ 34 914497284

**Comment by lpla** [comment]
Well, then just try latest 7.2 or master code and it should be fine. Let me know if you find another issue!

**Comment by jjmartinez-taiger** [comment]
Thank you Leo!


*José J. Martinez*

*VP of Technology*
www.taiger.com
+ 34 914497284
