### ISSUE TITLE
[Docker] Deduped error when bifixer: true and deduper: true

### ISSUE THREAD

**Issue by jjmartinez-taiger** [bitextor/bitextor#134]
**Describe the bug**
I get an error when bitextor reaches dedup step.

**To Reproduce**
I execute `bitextor -s default-en-es.yaml -j 8`
With this config.yaml:
```
bitextor: /opt/bitextor
hosts: ["www.diacorporate.es"]
httrack: true
permanentDir: /opt/results/default-en-es/bitextor-permanent-default-en-es
transientDir: /opt/results/default-en-es/bitextor-transient-default-en-es
temp: /opt/results/default-en-es/bitextor-transient-default-en-es
lang1: en
lang2: es
LANG1Tokenizer: /opt/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l en
LANG2Tokenizer: /opt/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l es
LANG1SentenceSplitter: /opt/bitextor/preprocess/moses/ems/support/split-sentences.perl -q -b -l en
LANG2SentenceSplitter: /opt/bitextor/preprocess/moses/ems/support/split-sentences.perl -q -b -l es
dic: /opt/dicts/en-es.dic

hunalignThreshold: 0.0

elrc: true
documentAligner: DIC
bifixer: true
bicleaner: /opt/bicleaner-models/en-es/training.en-es.yaml
bicleanerThreshold: 0.6
tmx: true
deduped: true
profiling: true

crawler: httrack

crawlTimeLimit: 2400s

crawlSizeLimit: 1G
crawlTld: false
crawlerNumThreads: 1
crawlerConnectionTimeout: 10
```
**Expected behavior**
Not failing in that step

**Desktop (please complete the following information):**
Ubuntu 16.04

**Additional context**
```[Mon Sep  9 15:53:14 2019]
rule deduped_tmx:
    input: /opt/results/default-en-es/bitextor-permanent-default-en-es/en-es.sent.xz
    output: /opt/results/default-en-es/bitextor-permanent-default-en-es/en-es.deduped.tmx.xz
    jobid: 2
    wildcards: l1=en, l2=es

[Mon Sep  9 15:53:14 2019]
Error in rule deduped_tmx:
    jobid: 2
    output: /opt/results/default-en-es/bitextor-permanent-default-en-es/en-es.deduped.tmx.xz

RuleException:
CalledProcessError in line 1501 of /opt/bitextor/snakemake/Snakefile:
Command 'sync; set -euo pipefail;  xzcat -T 0 -f /opt/results/default-en-es/bitextor-permanent-default-en-es/en-es.sent.xz | LC_ALL=C sort -t$' ' -r -k6,6 -k3,4 -T /opt/results/default-en-es/bitextor-transient-default-en-es --compress-program=gzip | /usr/bin/time -v ./bitextor-buildTMX-dedup.py --lang1 en --lang2 es -c url1,url2,seg1,seg2,hunalign,bicleaner,lengthratio,numTokensSL,numTokensTL | xz -T 0 > /opt/results/default-en-es/bitextor-permanent-default-en-es/en-es.deduped.tmx.xz' returned non-zero exit status 1.
  File "/opt/bitextor/snakemake/Snakefile", line 1501, in __rule_deduped_tmx
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job deduped_tmx since they might be corrupted:
/opt/results/default-en-es/bitextor-permanent-default-en-es/en-es.deduped.tmx.xz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /opt/bitextor/.snakemake/log/2019-09-09T145935.025319.snakemake.log
```

**Comment by lpla** [comment]
That's weird. Is there any other error output line before the context you pasted? This lines does not give any guess about what exactly broke (we already know that Snakemake error output format is a bit messed up).

**Comment by jjmartinez-taiger** [comment]
I don't see anything. @lpla is the config.yaml ok ? I need to remove duplicated TUs, so I added:
`dedup: true`

And `bifixer: true` also 

Anything wrong there? Anything missing?

**Comment by jjmartinez-taiger** [comment]
@lpla es bifixer: true lo que lo hace fallar. Si lo quitas, funciona.

**Comment by jjmartinez-taiger** [comment]
Tested in in foreground and got the error (it does not appear in the logs):
```
Traceback (most recent call last):
  File "./bitextor-buildTMX-dedup.py", line 119, in <module>
    previd = fieldsdict['seg1'] + "\t" + fieldsdict['seg2']
KeyError: 'seg1'
```

**Comment by lpla** [comment]
My bad, @jjmartinez-taiger, this was a set of untested configurations in latest release. Thanks for pointing this out.

Error output of `bifixer` was silenced. Now I reproduced the error and it is related to a missing dependency that @mbanon fixed a few days ago.

Please, pull my changes, submodule updates and rerun dependency installation instructions with these commands in the Bitextor root folder:

```
git checkout master
git pull
git submodule update --init --recursive --remote
pip3 install -r requirements.txt
pip3 install -r bicleaner/requirements.txt
pip3 install https://github.com/kpu/kenlm/archive/master.zip --install-option="--max_order 7"
pip3 install -r bifixer/requirements.txt
```

This should fix your issue.

**Comment by jjmartinez-taiger** [comment]
Great that you found that out!

Any plan to update it in the docker image? :) I'm using docker installation.


*José J. Martinez*

*VP of Technology*
www.taiger.com
+ 34 914497284

**Comment by lpla** [comment]
@amirkamran is the one maintaining the Docker image. I hope he could do it soon.

Also, I think that running the previous command set in `/opt/bitextor` should be a temporary fix until the image is updated (maybe `pip3` should be run as sudo).

**Comment by jjmartinez-taiger** [comment]
I will try and let you know. Thank you!


*José J. Martinez*

*VP of Technology*
www.taiger.com
+ 34 914497284

**Comment by jjmartinez-taiger** [comment]
Just to confirm that the proposed workaround fixes the problem.

Thanks, Leo !


*José J. Martinez*

*VP of Technology*
www.taiger.com
+ 34 914497284

**Comment by lpla** [comment]
Great!

Please, don't close this issue, so it will remind us to update the Docker image.

Thank you again and don't hesitate to open new issues!

**Comment by jjmartinez-taiger** [comment]
Sure! It may be as easy as execute the commands inside the official image
container and do `docker commit` That's how I generated mine :)

Regards,

Keep in touch !

**Comment by lpla** [comment]
Docker image updated! It is using the `master` code, not the stable release 7.2.1.

Closing issue.
