### ISSUE TITLE
WARCFiles option not supported in master

### ISSUE THREAD

**Issue by bhaddow** [bitextor/bitextor#136]
The WARCFiles option mentioned in the documentation is not supported. I assume the docs are out of sync with the code.

**Comment by bhaddow** [comment]
Also, bicleanerCorpusTrainingPrefix is required to be a list, but I am not sure why.

**Comment by lpla** [comment]
> The WARCFiles option mentioned in the documentation is not supported. I assume the docs are out of sync with the code.

It works for me using latest `master` code. I don't know why it doesn't work for you. Could you provide any error or configuration parameters?


> Also, bicleanerCorpusTrainingPrefix is required to be a list, but I am not sure why.

I don't see why either, in fact it looks like a bug, given that the Bicleaner model training rule only expects one corpus. I just pushed the change on `bicleanerCorpusTrainingPrefix` parameter validation.

**Comment by bhaddow** [comment]
My mistake about the WARCFiles. I thought I was on the latest version, but wasn't.

**Comment by lpla** [comment]
> Also, bicleanerCorpusTrainingPrefix is required to be a list, but I am not sure why.

We reverted the change and keep this parameter as a list because Bicleaner can be trained with several corpus (without forcing you to concatenate them before Bitextor).

Closing the issue.
