### ISSUE TITLE
Java build

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#14]
The current build system uses jar files for other projects and compiles code for this project.  

https://github.com/bitextor/bitextor/tree/52f2ba2e5ad1beb64bb7a3dd7c730cf922b8a49a/piped-boilerpipe

Wouldn't it be cleaner to have two options:
1. Just use a precompiled jar
2. Compile everything from source
This also means users you'll have the scripts to upgrade the jar.

**Comment by Lesbinary** [comment]
What is your opinion about Maven? I thought about using it for Tika and Boilerplate (the two only Java dependencies in Bitextor) when I started working in this project, but it became a low priority task.

Anyway, now we are quite sure that there are standard or well known Python libraries that could replace both Java programs and avoid all these problems with less code dependencies and fancier options. We expect finding those replacements and using them in release 7.0.
