### ISSUE TITLE
Make scripts monolingual when possible

### ISSUE THREAD

**Issue by mespla** [bitextor/bitextor#144]
Some scripts, such as bitextor-tokenize.py or extract_lett.py loop over languages to apply the same processing to files in different languages. This behaveour is against snakemake philosophy, and, in fact, we are loosing some advantages provided by a make-like tool:
 - it is not possible to parallelize processing across languages
 - when only of the files produced by these scripts is missing, all of them need to be produced again.

These scripts should process only produce one file at a time (only for one of the languages) and the logic to produce all the files corresponding to each language should be moved to Snakemake.

**Comment by lpla** [comment]
Fixed in 90e84cb6cf7a114f0b014b64e553411aa042ccae

Closing.
