### ISSUE TITLE
Applying sentence splitting twice

### ISSUE THREAD

**Issue by mespla** [bitextor/bitextor#145]
In master branch (commit fe239987e8a359b23dcde3386b49529d1462f5dd), the rule "docalign_extracted" in the Snakefile assumes sentence splitting has not been applied during preprocessing and applies it again. It is not clear to me in which scenario this behavior is necessary. Is this an error? If so, sentence splitting functionality can be removed from this script?

**Comment by zuny26** [comment]
This is resolved as of commit 939916d. Sentence splitting is only applied once now, as a part of the preprocessing step.
