### ISSUE TITLE
Using a trained NMT system

### ISSUE THREAD

**Issue by mzeidhassan** [bitextor/bitextor#147]
I don't want to train a new model in Marian. I have already an engine in my language combination "OpenNMT". 
Is there a way to use my current NMT engine? If yes, can you please explain how?

It would be great if we have the ability to hook up any NMT or SMT engine without the need to train a new model in Marian. 

Thanks in advance for your support. This new version is very different from previous versions, but I think it's a good step in the right direction. Congrats!

Thanks,
Mohamed

**Comment by lpla** [comment]
You are not forced to use Marian, or Moses. You can use any translator you want, but you need to be sure that the main engine or the program that is wrapping it receives sentences using stdin and print translations using stdout. Use `alignerCmd` configuration option to specify Bitextor your translation program path that works the way I said.

See the example: https://github.com/bitextor/bitextor#variables-for-document-alignment-using-external-mt

**Comment by mzeidhassan** [comment]
Thanks @lpla for your reply and follow-up. 
I am using Bitextor Docker image. Not super familiar with Docker though, so I don't know how it's possible to call the engine from within. My NMT engine has a rest API though. Any idea if there is a way to call the rest API directly and use this in dummy-translate.sh file?

**Comment by mzeidhassan** [comment]
@lpla one more thing:

Let's say I can get the stdout of my engine translation using this line:

cat life.en | ./mt translate --batch > life.de

What would be the exact correct command to use in dummy-translate.sh to use my engine as aligner?

Thanks again!

**Comment by lpla** [comment]
If you can run that `mt` binary by running a [shell of the Docker image](https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell), then you only need to provide `./mt translate` to `alignerCmd` option, as Bitextor will do the `cat life.en | ` and ` > life.de` with more processing and caching optimizations.

**Comment by mzeidhassan** [comment]
Thanks @lpla for your great support. So, I assume this mean that I don't need to modify or add anything to the dummy-translate.sh file, right?

**Comment by lpla** [comment]
`dummy-translate.sh` is only used as `alignCmd` in some tests and as a placeholder example, so no, you don't need to do anything with it.

**Comment by mzeidhassan** [comment]
Thanks @lpla for your continuous support. I appreciate it. I am closing this issue for now.
