### ISSUE TITLE
Validation error caused by sentenceSplitters, and wordTokenizers

### ISSUE THREAD

**Issue by mzeidhassan** [bitextor/bitextor#151]
Hi bitextor team,

I am installing bitextor in a virtual env. on Linux 16.04 using Python 3.6.8.

My yaml config file is:

```
bitextor: ~/bitextor/bin/bitextor
hosts: ["bbc.ae"]
httrack: false

dataDir: /home/user/permanent/data
permanentDir: ~/bitextor/bin/bitextor/ar-en/bbc/permanent
transientDir: ~/bitextor/bin/bitextor/ar-en/bbc/transient
temp: ~/bitextor/bin/bitextor/ar-en/bbc/transient/temp


wordTokenizers: "{
  'en': '~/bitextor/bin/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l en',
  'ar: '~/bitextor/bin/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l ar'
}"
sentenceSplitters: "{
  'en': '~/bitextor/bin/bitextor/preprocess/moses/ems/support/split-sentences.perl -q -b -l en',
  'ar: '~/bitextor/bin/bitextor/preprocess/moses/ems/support/split-sentences.perl -q -b -l ar'
}"


lang1: en
lang2: ar


dic: ~/bitextor/bin/bitextor/en-ar.dic
hunalignThreshold: 0
#elrc: true
elrc: false
documentAligner: DIC
#bicleaner: ~/bitextor/bin/bitextor/bicleaner-model/en-ar/training.en-ar.yaml
tmx: true
profiling: true
```
When I run the following command:

`./bitextor.sh -s config.ar-en_simple.yaml -j 4`

I get the following error:
```
> Validation error. Stopping. {'sentenceSplitters': ['must be of dict type'], 'wordTokenizers': ['must be of dict type']}
SystemExit in line 217 of /home/user/bitextor/bin/bitextor-v7.2.1/bitextor/snakemake/Snakefile:
None
  File "/home/user/bitextor/bin/bitextor-v7.2.1/bitextor/snakemake/Snakefile", line 222, in <module>
  File "/home/user/bitextor/bin/bitextor-v7.2.1/bitextor/snakemake/Snakefile", line 217, in ValidateArgs
  File "/home/user/bitextor/lib/python3.6/site.py", line 403, in __call__

```
As you can see in my config file, I have both sentenceSplitters and wordTokenizers. Any idea why I am getting this error?

Thanks

**Comment by mzeidhassan** [comment]
Also, according to the [config file](https://github.com/bitextor/bitextor/blob/44da8ab3e0702d4aa3463b69052587ded09228a0/snakemake/example/tests/default.en-fr.yaml), it seems 'dataDir' is not required, but I see my version of bitextor still complains about it if it doesn't exist in the config file.

`Starting bitextor
Validation error. Stopping. {'dataDir': ['unknown field'], 'sentenceSplitters': ['unknown field'], 'wordTokenizers': ['unknown field']}
`

**Comment by zuny26** [comment]
Hi @mzeidhassan,
It seems like our config file examples are not up to date, so right now it is better if you refer to the README. 
In your first example you don't need the quotation marks around `{}`, so you should write:
```
wordTokenizers: {
'en': '/bitextor/bin/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l en',
'ar: '/bitextor/bin/bitextor/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l ar'
}
sentenceSplitters: {
'en': '/bitextor/bin/bitextor/preprocess/moses/ems/support/split-sentences.perl -q -b -l en',
'ar: '/bitextor/bin/bitextor/preprocess/moses/ems/support/split-sentences.perl -q -b -l ar'
}
```
The `dataDir` field is actually required.
I'm keeping this issue open until we update the config files.
