### ISSUE TITLE
bitextor-train-document-alignment.py documentation

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#156]
Please add some context to this script.  When is it used?  So far as I can tell, it is the only script that uses tensorflow.  Is it necessary to have tensorflow in the requirements or could it be optional?

**Comment by lpla** [comment]
`tensorflow` is used in the dictionary-based document aligner (`bitextor-rank.py`), and this `bitextor-train-document-alignment.py` script is used to train the regressor model used in it. @mespla is working on replacing `tensorflow` and `keras` with `scikit.learn` regression models, which is already in `requirements.txt` for other parts of bitextor.

If you are not going to use this aligner, you are safe to keep `tensorflow` and `keras` uninstalled.
