### ISSUE TITLE
cython dependency not captured

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#157]
PyYAML requires cython to install with pip (and in turn PyYAML is in requirements.txt).  Yet cython only appears later in the documentation under the optional CLD3 dependency.

**Comment by lpla** [comment]
We though `pip` resolves dependencies for PyYAML and automatically install `cython` when installing `requirements.txt`, even if you don't use `cld3`. Looks like it doesn't. We added 'cython' to requirements.txt in e83910ea

Thank you for reporting.
