### ISSUE TITLE
jpype dependency not captured?

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#160]
I don't see jpype in the install instructions, even the optional ones.

**Comment by lpla** [comment]
It gets installed if you install `python-pdfextract` (in `requirements.txt`) and/or `python-boilerpipe` using `pip install git+https://github.com/slaveofcode/boilerpipe3.git`, which is also in `requirements.txt`.

Why should it be explicitly mentioned or installed?

**Comment by kpu** [comment]
Can we depend on jpype only if the PDF processing functionality is used?
