### ISSUE TITLE
CLD3 fails in language detection

### ISSUE THREAD

**Issue by mespla** [bitextor/bitextor#164]
**Describe the bug**
In some websites, CLD3 detects every document is in English. I wonder if this is due to the format of the documents: HTML. I have found [a discussion in the CLD3 github repository](https://github.com/google/cld3/issues/14#issuecomment-466258699) that makes me think that maybe CLD3 should be applied on the plain text.

**To Reproduce**
This can be reproduced if you try to detect the language of some web pages in the site https://mfa.gov.kg/kg/, for example the address https://mfa.gov.kg/kg/main/page?page_id=62 , which is clearly in Kyrgyz and not in English.

**Comment by lpla** [comment]
Fixing this bug requires a deeper code refactoring in `bitextor-warc2preprocess`, so, for now, a quick workaround is made in `w2p_cld3_htmlfix` branch.
