### ISSUE TITLE
Vocabulary file is still obligatory with the ParaCrawl aligner

### ISSUE THREAD

**Issue by bhaddow** [bitextor/bitextor#17]
Using the `--paracrawl-aligner-command` argument to specify the ParaCrawl aligner, I still get the message `THE VOCABULARY FILE WAS NOT SET: USE OPTION -v` if I do not supply a dictionary. Supplying an empty dictionary (just the language codes) gets around this, but I do not think a dictionary should be required. It can be used by hunalign, but there it's optional (afaik)

**Comment by Lesbinary** [comment]
You are right.

When you give a dictionary/vocabulary to Bitextor it uses it in Hunalign and in Bitextor default document aligner, which works based on the vocabulary matches (among other features). Now that we have Paracrawl Aligner implemented, the dictionary should be clearly optional.

Next commit should fix it.
