### ISSUE TITLE
Validation error with customNBPs

### ISSUE THREAD

**Issue by Bachstelze** [bitextor/bitextor#175]
The followoing Error occurs when the customNBPs is declared like in the readMe:
`Validation error. Stopping. {'customNBPs': ['unknown field']}`
I use the docker installation and the snakemake config template.

**Comment by lpla** [comment]
Docker was not updated with latest `master` branch changes. I just updated `bitextor` with its dependencies in the docker image and run our small test set in it. Please, download the latest image and try again.

**Comment by Bachstelze** [comment]
Snakemake is running now. Thank you for the quick fix.
