### ISSUE TITLE
Build fails on zipporah

### ISSUE THREAD

**Issue by bhaddow** [bitextor/bitextor#18]
Clean checkout, running `make` gives
```
make[1]: Entering directory '/mnt/saga0/bhaddow/code/bitextor/test'
Making all in zipporah
make[2]: Entering directory '/mnt/saga0/bhaddow/code/bitextor/test/zipporah'
make[2]: *** No rule to make target 'generate-bow-xent', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/mnt/saga0/bhaddow/code/bitextor/test/zipporah'
Makefile:507: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mnt/saga0/bhaddow/code/bitextor/test'
Makefile:390: recipe for target 'all' failed
make: *** [all] Error 2
```

Removing `generate-bow-xent` from `zipporah/Makefile.am` enables build to succeed, but not sure if that is the right solution.

**Comment by Lesbinary** [comment]
I have it working well. Maybe it is related to the change I made today migrating the `generate-bow-xent` script to the submodule from the original repository. I think that if you don't update all submodules you won't be able to compile it again.

Try to run this: `git submodule update --init --recursive`

**Comment by Lesbinary** [comment]
Okay, I tried with a clean environment and it is an issue. I will fix it and let you know.
