### ISSUE TITLE
Is mining parallel corpus for English - Nepali language in progress ?

### ISSUE THREAD

**Issue by mani-rai** [bitextor/bitextor#181]
Apologies because this issue is not bug nor feature request. This is just an enquiry.

I wanted to mine parallel corpus for my thesis as well. But found Bitextor which seems to be already mining english nepali corpus as well. But wanted to make sure, if mining english nepali pair is stopped or in progress and will be realeased further or not.

Also there are few confusions I am having if you don't mind:

1. I looked at english nepali pair corpus manually, downloaded from paracrawl site. And confused if the aligned Nepali sentence is machine translated or scraped from web. Its because I found Nepali sentence is pretty bad syntactically. If the sentence was scraped from some websites, I think it shouldn't be this bad. It's kind of like machine translated sentences.

2. Also I found that sources (websites) are mostly foreign websites. And in most case, foreign websites don't usually support Nepali language becuase of small audience.

3. I looked at the process of mining. Looking at it, it doesn't seems translated sentences are incorporated in corpus. So wanted to assure this for official maintainers.

4. Also trying to understand LASER scores. Just to save some time, can somebody tell me the LASER score range that is considered bad or good?

Apologies again.

**Comment by phikoehn** [comment]
Yes, the dat is web crawled and very noisy. We try to address this by providing quality scores. In this case, these are LASER scores that have shown to be most accurate for this data set. The higher the score the better. Thresholds for inclusion may be in the range of 0.9 to 1.05, based on where you make the big/clean trade-off. For more information about this particular data set, see: https://www.aclweb.org/anthology/W19-5404/
