### ISSUE TITLE
You can guide more? 

### ISSUE THREAD

**Issue by NVFALCON** [bitextor/bitextor#191]
You can guide more? 
Im run on docker and repair config.yaml I get it back:

root@cfb35fea42e8:/opt/bitextor# sh ./bitextor.sh -s ./snakemake/example/tests/config.yaml

./bitextor.sh: 37: ./bitextor.sh: [[: not found
./bitextor.sh: 85: ./bitextor.sh: [[: not found
WARNING: dictionary /root/permanent/en-fr.dic was not found. Provide correct path to the dictionary or specify initCorpusTrainPrefix
Validation error. Stopping. {'bicleanerCorpusTrainingPrefix': ['required field']}
SystemExit in line 248 of /opt/bitextor/snakemake/Snakefile:
None
  File "/opt/bitextor/snakemake/Snakefile", line 252, in <module>
  File "/opt/bitextor/snakemake/Snakefile", line 248, in validate_args
  File "/usr/lib/python3.6/_sitebuiltins.py", line 26, in __call__

**Comment by lpla** [comment]
Hi. Try running `bash ./bitextor.sh -s ./snakemake/example/tests/config.yaml` instead, as `bitextor.sh` has some code that `sh` cannot run.
