### ISSUE TITLE
MissingInputException in line 2004 of /opt/bitextor/snakemake/Snakefile:

### ISSUE THREAD

**Issue by zbhatti-dev** [bitextor/bitextor#194]
Missing input files for rule tokenize_file_l1:
/home/lpla/Europarl.en-fr.en.xz

I am running from docker

**Comment by zbhatti-dev** [comment]
OK I think I know why this is; because the ditionary is missing, but where do I get the dictionary from and what format should it be in, I can find an example file for this

**Comment by zbhatti-dev** [comment]
OK I downloaded a dictionary put it in the right location but still getting the above error...maybe my file paths are wrong to the the dictionary but have tried multiple methods

**Comment by zbhatti-dev** [comment]
dictionary is being found; but still the same error, I dont understand why its trying to generate a dictionary even though I have provided it with one

**Comment by lpla** [comment]
Hi. Could you paste here the specific error you are having?

**Comment by zbhatti-dev** [comment]
Hi Ipla, thanks for getting back to me...finally resolved it...the postprocessing bicleaner-model doesnt seem to download within docker, so it seemed to be completely empty...so had to copy across manually...thanks for getting back; but there is another issue I have it, will raise separate issues; I am trying to do this for urdu language...but initially just trying to get it up and running first
