### ISSUE TITLE
Error in rule bicleaner

### ISSUE THREAD

**Issue by zbhatti-dev** [bitextor/bitextor#196]
Error in rule bicleaner:
    jobid: 10
    output: /opt/bitextor/transient-default-en-fr-small/greenpeace/hunalign.bicleaner.scores.xz
    shell:
        
        slang=$(egrep "source_lang" /bicleaner-model/en-fr.yaml | cut -d " " -f 2)
        if [ "$slang" == "fr" ]; then
          xzcat -T 0 -f /opt/bitextor/transient-default-en-fr-small/greenpeace/hunalign.bifixer.xz |
           /opt/bitextor/preprocess/bin/cache -k 6 python3 /opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py --score_only -q - - /bicleaner-model/en-fr.yaml |
          paste <(xzcat -T 0 /opt/bitextor/transient-default-en-fr-small/greenpeace/hunalign.bifixer.xz) - |
          xz -T 0 > /opt/bitextor/transient-default-en-fr-small/greenpeace/hunalign.bicleaner.scores.xz
        else
          xzcat -T 0 -f /opt/bitextor/transient-default-en-fr-small/greenpeace/hunalign.bifixer.xz |
          awk ' BEGIN {FS="	"; OFS="	"} { t = $3; $3 = $4; $4 = t; print;}' |
           /opt/bitextor/preprocess/bin/cache -k 6 python3  /opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py --score_only -q - - /bicleaner-model/en-fr.yaml |
          paste <(xzcat -T 0 /opt/bitextor/transient-default-en-fr-small/greenpeace/hunalign.bifixer.xz) - |
          xz -T 0 > /opt/bitextor/transient-default-en-fr-small/greenpeace/hunalign.bicleaner.scores.xz
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by zbhatti-dev** [comment]
I am using the bicleaner stuff downloaded from the repositories flagged in github...is there any way to bypass the bicleaner?  I dont think it was mandatory previously...

**Comment by zbhatti-dev** [comment]
OK I just commented out the bicleaner...

**Comment by zbhatti-dev** [comment]
yes I am trying to use the bicleaner, but following error being seen:

Error in rule bicleaner:
    jobid: 10
    output: /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bicleaner.scores.xz
    shell:
        
        slang=$(egrep "source_lang" /opt/bitextor/bicleaner-model/en-fr.yaml | cut -d " " -f 2)
        if [ "$slang" == "fr" ]; then
          xzcat -T 0 -f /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bifixer.xz |
           /opt/bitextor/preprocess/bin/cache -k 6 python3 /opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py --score_only -q - - /opt/bitextor/bicleaner-model/en-fr.yaml |
          paste <(xzcat -T 0 /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bifixer.xz) - |
          xz -T 0 > /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bicleaner.scores.xz
        else
          xzcat -T 0 -f /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bifixer.xz |
          awk ' BEGIN {FS="	"; OFS="	"} { t = $3; $3 = $4; $4 = t; print;}' |
           /opt/bitextor/preprocess/bin/cache -k 6 python3  /opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py --score_only -q - - /opt/bitextor/bicleaner-model/en-fr.yaml |
          paste <(xzcat -T 0 /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bifixer.xz) - |
          xz -T 0 > /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bicleaner.scores.xz
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by zbhatti-dev** [comment]
Traceback (most recent call last):
  File "/opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py", line 135, in initialization
    args.good_examples = metadata_yaml["good_examples"]
KeyError: 'good_examples'
terminate called after throwing an instance of 'util::EndOfFileException'
  what():  End of file
/bin/bash: line 12:   376 Done                    xzcat -T 0 -f /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bifixer.xz
       377                       | awk ' BEGIN {FS="	"; OFS="	"} { t = $3; $3 = $4; $4 = t; print;}'
       378 Aborted                 | /opt/bitextor/preprocess/bin/cache -k 6 python3 /opt/bitextor/bicleaner/bicleaner/bicleaner_classifier_lite.py --score_only -q - - /opt/bitextor/bicleaner-model/en-fr.yaml
       379                       | paste <(xzcat -T 0 /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bifixer.xz) -
       380                       | xz -T 0 > /opt/bitextor/transient-default-en-fr-small/sentence-pair-testing/hunalign.bicleaner.scores.xz
[Sat Mar  6 15:37:26 2021]

**Comment by lpla** [comment]
Seems like you are using a modern model for Bicleaner (probably for version 0.14) and your Bitextor installation still uses a previous one (0.13 IIRC). Try using the ones for bicleaner 0.13: https://github.com/bitextor/bicleaner-data/releases/tag/v1.3

**Comment by zbhatti-dev** [comment]
same error again...I am just thinking maybe I am loading the the bicleaner-model in the wrong place??? I am putting it all where in the following place:
bicleaner: /opt/bitextor/bicleaner-model/en-fr.yaml # Use bicleaner model for parallel data filtering

so I am putting all the contents in here /opt/bitextor/bicleaner-model/

**Comment by zbhatti-dev** [comment]
same error again...have checked file locations all seems OK...

**Comment by zbhatti-dev** [comment]
RESULT...brilliant what you suggested worked 0.13 version fantastic!
