### ISSUE TITLE
Install Alcazar

### ISSUE THREAD

**Issue by gaetanboulard** [bitextor/bitextor#197]
I seems the dependency alcazar has disappeared, making a bitextor manual installation quite tricky.
As a workaround I have manually copied the alcazar modules from a previous installation of bitextor I had lying around, but that option isn't available for everyone.

Is the alcazar repository indeed gone or am I missing something ?

**Comment by lpla** [comment]
Hi. Yes, Alcazar is gone. But yesterday I pushed a commit deleting all references to it from master branch. Did you pull latest changes?

**Comment by gaetanboulard** [comment]
Ah no, I was working on it 2 days ago. Seems I just missed out on the update.
I will try again and see how it goes

**Comment by gaetanboulard** [comment]
All good with the new update. Thank you
