### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dinosaxon** [bitextor/bitextor#2]
Dear devs

I cloned the code and  trying to ./configure I get the error "bash: ./configure: No such file or directory"

Could you please help to install?

Thanks

**Comment by Lesbinary** [comment]
Hi @dinosaxon.

We forgot to update the README.md file explaining the new way to install Bitextor. In the Wiki is updated and better explained, but after the next commit it will be better explained in README.md also.

Just do `autogen.sh` instead of `configure`:

```
 user@pc:~$ ./autogen.sh
 user@pc:~$ make
 user@pc:~$ sudo make install
```

**Comment by dinosaxon** [comment]
Hi,

Thank you for your prompt reply. I am now facing another problem with python-magic.

I have installed python-magic-0.4.15 using pip however it is not possible to run m=magic.open(magic.MAGIC_NONE). Python says that module 'magic' has no attribute "open".

I also tried to install using apt-get but the package is not recognised by Ubuntu 16.04 and python3.

Could you please advise?

**Comment by Lesbinary** [comment]
Hi again @dinosaxon. Currently, our project is only compatible with Python 2. There is a branch in which we are trying to make it fully compatible with Python 3.

Regarding the conflict with Magic, try to uninstall the package python-magic-0.4.15 from pip and keep only the magic package from apt.
