### ISSUE TITLE
Inconsistent behaviour of paths in .yaml file

### ISSUE THREAD

**Issue by mlforcada** [bitextor/bitextor#200]
**Describe the bug**
One cannot use "~" in some stanzas of the YAML file, but can use it in some others.

**To Reproduce**
Give a "~" path when specifying dic: in the YAML file.

**Expected behavior**
I'd expect "~" to be expanded as in other stanzas of the YAML file. (permanentDir:, transientDir:, etc.)

**Desktop (please complete the following information):**
 - OS: Ubuntu GNU/Linux 20.04
 - bitextor installed from conda following README.md in snake_performance branch:
 ```
bitextor                  8                  138_ge4bf4f9    bitextor
```

**Comment by lpla** [comment]
Closed #200 via https://github.com/bitextor/bitextor/commit/7494a43c025c8f0565f664b8cb7e7978bd9172a7.
