### ISSUE TITLE
How do you compare two different domains

### ISSUE THREAD

**Issue by zbhatti-dev** [bitextor/bitextor#202]
Hi

I am running bitextor, and I want it to compare pages across two websites...so one website is in English and other is in French; are there particular configuration settings I can use to achieve this?

thanks

**Comment by lpla** [comment]
Hi. This a feature is implemented in the still-in-development Bitextor 8.0, but it is not in master branch or 7.X versions.

If you want to align two or more different domains in Bitextor 7 (the one that comes in the docker version as today), you need to provide Bitextor the WARC file (or files) of the domains you want to align by using the config option [`WARCFiles`](https://github.com/bitextor/bitextor#data-sources), as it treats all provided WARC files as one domain. You can obtain WARC files from previous Bitextor runs looking in the `dataDir` folder or manually using a crawler like `wget`.

In the next Bitextor release (8.0, being developed in `snake_performance` branch in case you want to give a try), you can use config option `shards: 0` forcing all domains and WARCs provided to Bitextor being compared with all of them.

**Comment by lpla** [comment]
Bitextor 8.0 code has reached `master` branch and soon will be officially released. I added my previous comment into the documentation section for `shards`, in case anyone else wants to run this use case. Thank you.
