### ISSUE TITLE
Problem when run bitextor using document aligner NMT

### ISSUE THREAD

**Issue by lumosnysm** [bitextor/bitextor#205]
I run bitextor with config just like the documentation
```
...
initCorpusTrainPrefix: ['/home/user/Europarl.en-fr.train']
initCorpusDevPrefix: ['/home/user/Europarl.en-fr.dev']
initCorpusTestPrefix: ['/home/user/Europarl.en-fr.test']

marianDir: /home/user/marian-dev
mosesDir: /home/user/mosesdecoder
subwordNmtDir: /home/user/subword-nmt

nmtVocabSize: 50000

LANG2Detokenizer: "/home/user/mosesdecoder/scripts/tokenizer/detokenizer.perl -l fr"

gpuId: 0

marianArgs: [" --optimizer-delay 1", "--mini-batch-fit", "--mini-batch 1000", "--maxi-batch 1000", "--overwrite", "--keep-best", "--valid-metrics perplexity", "--valid-log valid.log", "--log train.log", "--dropout-rnn 0.2", "--dropout-src 0.2", "--dropout-trg 0.2 ", "--cost-type ce-mean-words", "--layer-normalization", "--exponential-smoothing", "--tied-embeddings", "--valid-metrics bleu"]
...
```
but it throwing this error
```
KeyError in line 23 of /workspace/thviet/bitextor/snakemake/nmt/Snakefile:
'LANG1Tokenizer'
  File "/workspace/thviet/bitextor/snakemake/nmt/Snakefile", line 23, in <module>
```
Can you help me to fix this?, thank you.

**Comment by lpla** [comment]
Hi. Which version of Bitextor are you using?

**Comment by lumosnysm** [comment]
I am using the master branch of this repo.

**Comment by lpla** [comment]
It is a bug. Just pushed a workaround to master. Pull these changes and try to run Bitextor again. Let me know if this works or not, as I couldn't test it (I don't have a Marian environment with GPU available right now).

Thank you for reporting!

**Comment by lumosnysm** [comment]
@Ipla thanks for your quick support
Do i need to set the `marianModelFile` in the config file as i don't see it in the documentation
I got this error
```
KeyError in line 98 of /workspace/thviet/bitextor/snakemake/nmt/Snakefile:
'marianModelFile'
  File "/workspace/thviet/bitextor/snakemake/nmt/Snakefile", line 98, in <module>
```

**Comment by lpla** [comment]
Yes. We forgot to add that one to the README.md. Thank you for reporting it!

**Comment by lpla** [comment]
Hi. We decided to remove MarianNMT training settings and code from our last push to master towards Bitextor 8.0 release, as it is deprecated. If you want to keep using it, you will need to use Bitextor 7.x code. Closing issue.
