### ISSUE TITLE
pip installation advice incorrect on Ubuntu 16.04

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#22]
Ubuntu 16.04 is rather inconsistent when it comes to Python versioning.  

Just calling `python` yields 2.7.12:
```
python --version
Python 2.7.12
```
But when I call pip it's version 3:
```
head -n 1 $(which pip)
#!/usr/bin/python3
```

So when I get this error message:
```
configure: error: this package requires iso639 for Python. Please, install with 'sudo pip install iso-639' and try again.
```
running that command installs the package for Python 3, but not 2.7.  But configure is checking for 2.7 :-(.  To be pedantic, I need to run
```
sudo pip2.7 install iso-639
```

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

**Comment by Lesbinary** [comment]
That's weird. Here we have vanilla Ubuntu 16.04 and 18.04 and this problem does not exist. `pip` only points `pip2` in all machines if installed with `apt python2-pip`. Are you using virtualenv or Anaconda? Or maybe you installed `pip` with easy_install? But in any case, that `pip2.7` command should be fine if it installs the package for `python2`. We support the configuration using the packages we defined in `README.md`.

**Comment by kpu** [comment]
This might be something bizarre happening on our cluster downstairs.  I haven't tried a stock Ubunto 16.04.

**Comment by Lesbinary** [comment]
Anyway, in Bitextor 7.0 this problem will be automatically fixed as the whole code will be in Python 3 and all dependencies will be installed using `pip3`.
