### ISSUE TITLE
Handle submodules in build system

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#23]
The build system should check out submodules if needed.  
Currently things just fail with:
```
make  all-recursive
make[1]: Entering directory '/home/heafield/bitextor'
Making all in zipporah
make[2]: Entering directory '/home/heafield/bitextor/zipporah'
g++ zipporah/tools/generate-bow-xent.cc -o generate-bow-xent -std=c++11
g++: error: zipporah/tools/generate-bow-xent.cc: No such file or directory
g++: fatal error: no input files
compilation terminated.
Makefile:493: recipe for target 'generate-bow-xent' failed
make[2]: *** [generate-bow-xent] Error 1
make[2]: Leaving directory '/home/heafield/bitextor/zipporah'
Makefile:507: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/heafield/bitextor'
Makefile:390: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Lesbinary** [comment]
In https://github.com/bitextor/bitextor/wiki#requirements and https://github.com/bitextor/bitextor/blob/master/README.md#dependencies installation instructions we wrote that submodules dependencies should be installed with `git clone --recurse-submodules https://github.com/bitextor/bitextor.git` if you are cloning this repo from scratch or in case you are downloading a tarball or already did a simple clone, just do `git submodule update --init --recursive`.

But yes, we should detect that when installing to avoid confusing messages. I will work on that.

**Comment by kpu** [comment]
Where does it say this in `INSTALL`?
