### ISSUE TITLE
Only first file in warc file appears to be processed when "directories" is used as data source

### ISSUE THREAD

**Issue by jonwolds** [bitextor/bitextor#254]
I wanted to create a tmx file from a set of French and English pdf files (pdf-extract is installed and working). The files are contained in two directories (one per language as it happens). 

A tmx file is created, but only the first file contained in each warc archive (one warc is created per directory in the data/generated_warc directory) is used. If I remove the two files used in the first run, delete the bitextor data directories and then repeat, again only the first file contained in each warc archive is used (but obviously different files to the first run, and files that were not used in the first run).

I would have expected all the pdf files in both directories to have been used.

Below is the first part of my config file.

Apologies in advance if I've missed something very obvious!

Cheers,

Jon

```
permanentDir: ~/permanent
transientDir: ~/transient
tempDir: ~/transient

# DATA SOURCES - CRAWLING
# crawler: "wget"
# crawler: heritrix
# heritrixPath: /home/user/heritrix-3.4.0-20190418
# heritrixUrl: "https://localhost:8443"
# heritrixUser: "root:root"

directories: ["/opt/app/marian/model/gri/en/pdf", "/opt/app/marian/model/gri/fr/pdf"]
#crawlTimeLimit: "86400s" # 24 hours

# DATA SOURCES - WARC FILES

# PREPROCESSING
shards: 8 # 2^8 = 256 shards
batches: 1024 # each shard split into chunks of 1024 MB
paragraphIdentification: true
additionalMetadata: true
PDFprocessing: pdfextract
PDFextract_configfile: /home/docker/bitextor/pdf-extract/PDFExtract.json
PDFextract_sentence_join_path: /home/docker/bitextor/pdf-extract/sentence-join/sentence-join.py
PDFextract_kenlm_path: /home/docker/kenlm/build/bin
lang1: 'en'
lang2: 'fr'

**Comment by aarongaliano** [comment]
Hi, thank you for reporting this issue.

The problem seems to be related to pdf-extract.  I will try to debug this, but in the meantime, can you try using Apache Tika?
In our tests, Apache Tika works better and faster than pdf-extract, so it might be useful for you.
You just need to change the `PDFprocessing` parameter to `PDFprocessing: apacheTika` and delete the rest of the pdf-extract parameters.

**Comment by jonwolds** [comment]
Many thanks for your help. How is Apache tika called by bitextor? (so I can install it in the correct location)
