### ISSUE TITLE
Bitextor usage

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#260]
Hi guys!

Wondering if you have a list of other projects or corpora that has been created with the Bitextor/Paracrawl software. I can only think of JParacrawl but I suspect there are more.

Flicking through citations, nothing stands out

**Comment by lpla** [comment]
Hi, Hieu! It's nice to hear from you.

We created the MaCoCu corpora using Bitextor and additional Bitextor's organization software: https://macocu.eu

Not corpora, but seems like `warc2text` is being used in to train the models in the HPLT project: https://hplt-project.org

**Comment by mbanon** [comment]
Hi there!
Also used in Europat https://europat.net/,  at least in part ( https://aclanthology.org/2022.lrec-1.78/ )

**Comment by mespla** [comment]
Hi Hieu!

There are a few more corpora created using Bitextor. The corpora created in the GoURMET project (https://opus.nlpl.eu/GoURMET.php) were produced using it. Also, the parallel corpora produced in the AbuMaTran project used Bitextor, even though it was an older version:

- https://www.clarin.si/repository/xmlui/handle/11356/1059
- https://www.clarin.si/repository/xmlui/handle/11356/1061
- https://www.clarin.si/repository/xmlui/handle/11356/1058
- https://www.clarin.si/repository/xmlui/handle/11356/1060
- https://www.clarin.si/repository/xmlui/handle/11356/1049

**Comment by hieuhoang** [comment]
Thanks guys. Good to know it's still ticking along
