### ISSUE TITLE
404 Error Accessing Latest Paracrawl Bonus Release Raw Files

### ISSUE THREAD

**Issue by Ssloto** [bitextor/bitextor#261]
Hi all,
I'm excited by the recent announcement of bonus languages for Paracrawl for English-Azerbaijani, Armenian, and Tajik. Unfortunately, when I try to download the raw files, I get a 404 error while using the urls at the website. Other files seem to work okay.

Here are the links that do not work for me:
* http://web-language-models.s3-website-us-east-1.amazonaws.com/paracrawl/bonus/en-azj-v1.classified.gz
* http://web-language-models.s3-website-us-east-1.amazonaws.com/paracrawl/bonus/en-tg-v1.classified.gz
* http://web-language-models.s3-website-us-east-1.amazonaws.com/paracrawl/bonus/en-hy-v1.classified.gz

Example error
```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: paracrawl/bonus/en-tg-v1.classified.gz
```

**Comment by ZJaume** [comment]
Hi @Ssloto,

Thank you for pointing this out! The names of the bonus releases are bit of a mess and we posted the wrong urls. These three languages do not have the `-v1` suffix in their names, if you try with that, it should work. We are now updating the website links.

**Comment by ZJaume** [comment]
All the links in the website should be working now.

**Comment by Ssloto** [comment]
Thanks!
