### ISSUE TITLE
webdir2ett and ett2lett give no output

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#28]
[cn.iherb.com.tar.gz](https://github.com/bitextor/bitextor/files/2374513/cn.iherb.com.tar.gz)

When I try to run the following command on the above (2-page) website
   $BITEXTOR/bitextor-webdir2ett webdir/cn.iherb.com | $BITEXTOR/bitextor-ett2lett -l en,zh
it gives me no output.

However, it works if I use slightly older bitextor scripts that are in Malign. 
  https://github.com/paracrawl/Malign/tree/master/crawl/bitextor
Would like to use the original bitextor scripts rather than maintain our own

**Comment by Lesbinary** [comment]
Should be working now. If you are including bitextor-ett2lett to Malign, take into account the path for the Java modules and importing the new script, bitextor-lett-language-detector.

If anything else happens, just let me know.
