### ISSUE TITLE
Reference files by path relative to self

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#30]
Bitextor scripts sometimes need to call other scripts.  The best practice is that an executable determines where it is located then calls relative to that path.  

For example `foo.sh` can call `bar.sh` in the same source directory:
```bash
exec "$(dirname "$0")"/bar.sh
```
or in python using `__file__`

There should be no `__PREFIX__` in the source.

**Comment by lpla** [comment]
I made a commit to a branch named `no-prefix` (see above). I think those changes made what you described, but if anything else is needed just tell me.

**Comment by lpla** [comment]
I merged the branch into master. Please, reopen if necessary.

**Comment by kpu** [comment]
It looks like you simplified my
`"$(dirname "$0")"`
to
`$(dirname $0)`
Those quotes were there for a reason: to continue working if there is a space in the path to bitextor.

**Comment by lpla** [comment]
You are right. I changed that and briefly tested with a path that contains spaces and now it works. Thanks!
