### ISSUE TITLE
Killing script compilation: __ENV__ __PYTHON__

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#31]
Now thaw #30 is closed, let's talk about removing script compilation entirely.  Here's a summary of how bitextor genericizes over `env` and `python`:

https://github.com/bitextor/bitextor/blob/master/textsanitizer.py
`#!/usr/bin/env python`

https://github.com/bitextor/bitextor/blob/master/bitextor-identifyMIME.py
`#!__ENV__ __PYTHON__`

https://github.com/bitextor/bitextor/blob/master/bitextor-dir2warc.py
`#!__ENV__ python3`

So bitextor already doesn't genericize over these variables.  Can we just assume `/usr/bin/env` ?

**Comment by hieuhoang** [comment]
The snakemake version of bitextor runs without scripts being 'compiled'. Lets keep it that way

**Comment by lpla** [comment]
Yes. This is already fixed in 'bitextor-malign' branch, we hope to merge this branch into master soon.
