### ISSUE TITLE
User-specified tokenizer

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#32]
The user should be able to specify their own tokenizer for each language.  Not the current mishmash of NLTK or moses tokenizer.  This would be necessary for e.g. Chinese to customize segmentation.  But also low-resource languages are unlikely to have a prepacked tokenizer.

**Comment by kpu** [comment]
See the `mosestokenizer` python class for an example of wrapping a command-line tokenizer without buffering.

**Comment by lpla** [comment]
I finished the integration of the user-specified sentence and word tokeniser in `bitextor-malign` branch, using ToolWrapper (the Pỳthon class from `mosestokenizer`) and ExternalTextProcessor (from `malign`). 

I will leave this issue open for bugs, regressions or any other related issues.

**Comment by lpla** [comment]
Code now in master, and in next release this week. After 3 months testing it I will close this thread. If any related issue pops up, open a new one.
