### ISSUE TITLE
creepy crawler hangs

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#33]
python3 /home/hieu/permanent/software/bitextor/bitextor-crawl.py -t 10s -j 2 http://2002.presidentielles.net  > t

Doesn't exit but doesn't download any more either

**Comment by JiaYueHuang** [comment]
This problem I also encountered too.
I think the bitextor-crawl.py exit some problem (I am finding now).

You can test the bitextor-crawl.py use the following url:
http://worldoftanks.asia

And you will find that it will take several days to crawl the web data (i try to use the bitextor to crawl this url 3 days and use the option -I to output the intermediate files and found that the result was hundreds of Gigabytes and doesn't stop , so it take several days and without final output result. )

**Comment by mespla** [comment]
Closed in commit a12e98f3292607cfe197cf8f2f402dbc07f1cd08
