### ISSUE TITLE
httrack error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#34]
Running
   bitextor-webdir2warc.sh website > /dev/null
I get this error
   Traceback (most recent call last):
  File "/home/hieu/permanent/software/bitextor/bitextor-dir2warc.py", line 23, in <module>
    warc_record = warc.WARCRecord(payload=content,headers={"WARC-Target-URI":url.decode("utf8")})
AttributeError: 'NoneType' object has no attribute 'decode'

Tar file of website folder attached

[website.zip](https://github.com/bitextor/bitextor/files/2558715/website.zip)

**Comment by mespla** [comment]
Commit e858ea4046c86fab24675182c7cb1470e2b0053b fixes the  bug

**Comment by hieuhoang** [comment]
cheers
