### ISSUE TITLE
{BITEXTORINSTALL} install error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#36]
I'm getting this error

RuleException:
CalledProcessError in line 539 of /home/hieu/workspace/github/paracrawl/bitextor.malign/snakemake/Snakefile:
Command ' set -euo pipefail;  /home/hieu/permanent/software/bitextor/bitextor-rank.py -m /home/hieu/permanent/software/bitextor/{BITEXTORINSTALL}/share/bitextor/model/keras.model -w /home/hieu/permanent/software/bitextor/{BITEXTORINSTALL}/share/bitextor/model/keras.weights < /home/hieu/transient/en-fr/activeboard.1.urlsoverlap > /home/hieu/transient/en-fr/activeboard.1.rank ' returned non-zero exit status 1.

I would suggest we leave {BITEXTORINSTALL} until after the pipeline has been completed and thoroughly test. Installing bitextor should be invisible to the code, at the moment its causing headache

**Comment by hieuhoang** [comment]
deleting {BITEXTORINSTALL} https://github.com/bitextor/bitextor/commit/8c827265b72d21b02420d4d5bbda6a35d0f7d76d

1 less thing to worry about

**Comment by mespla** [comment]
Without BITEXTORINSTALL variable snakemake cannot find models, tika, or hunalign. To have a pipeline that works both on an installation and on the source code, we should either have two variables (one with the path to the installation [BITEXTORINSTALL] and one with the path to the source code  [BITEXTOR]) or we have to move everything in the repository so it looks like the installation directory (with scripts and executables in a bin sub-dir, models in a share sub-dir, etc.)
