### ISSUE TITLE
Not able to compile bleualign

### ISSUE THREAD

**Issue by mespla** [bitextor/bitextor#38]
I am trying to compile bleualign-cpp, but I got an error related to autotools. I have tried with libtools 1.62, 1.65, and 1.67, but get the same error. I have also tried on Ubuntu 16 and 18. Tried both with the version installed with apt install and with conda. The error I get is:

libbleualign_cpp_lib.a(CompressedWriter.cpp.o): In function `utils::CompressedWriter::CompressedWriter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
CompressedWriter.cpp:(.text+0x282): undefined reference to `boost::iostreams::lzma::best_compression'
libbleualign_cpp_lib.a(CompressedWriter.cpp.o): In function `boost::iostreams::detail::lzma_compressor_impl<std::allocator<char> >::lzma_compressor_impl(boost::iostreams::lzma_params const&)':
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEEC2ERKNS0_11lzma_paramsE[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEEC5ERKNS0_11lzma_paramsE]+0x19): undefined reference to `boost::iostreams::detail::lzma_base::lzma_base()'
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEEC2ERKNS0_11lzma_paramsE[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEEC5ERKNS0_11lzma_paramsE]+0x5e): undefined reference to `boost::iostreams::detail::lzma_base::~lzma_base()'
libbleualign_cpp_lib.a(CompressedWriter.cpp.o): In function `boost::iostreams::detail::lzma_compressor_impl<std::allocator<char> >::~lzma_compressor_impl()':
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEED2Ev[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEED5Ev]+0x1e): undefined reference to `boost::iostreams::detail::lzma_base::reset(bool, bool)'
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEED2Ev[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEED5Ev]+0x36): undefined reference to `boost::iostreams::detail::lzma_base::~lzma_base()'
libbleualign_cpp_lib.a(CompressedWriter.cpp.o): In function `void boost::iostreams::detail::lzma_base::init<std::allocator<char> >(boost::iostreams::lzma_params const&, bool, boost::iostreams::detail::lzma_allocator<std::allocator<char>, boost::iostreams::detail::lzma_allocator_traits<std::allocator<char> >::type>&)':
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail9lzma_base4initISaIcEEEvRKNS0_11lzma_paramsEbRNS1_14lzma_allocatorIT_NS1_21lzma_allocator_traitsIS9_E4typeEEE[_ZN5boost9iostreams6detail9lzma_base4initISaIcEEEvRKNS0_11lzma_paramsEbRNS1_14lzma_allocatorIT_NS1_21lzma_allocator_traitsIS9_E4typeEEE]+0x66): undefined reference to `boost::iostreams::detail::lzma_base::do_init(boost::iostreams::lzma_params const&, bool, void* (*)(void*, unsigned long, unsigned long), void (*)(void*, void*), void*)'
libbleualign_cpp_lib.a(CompressedWriter.cpp.o): In function `boost::iostreams::detail::lzma_compressor_impl<std::allocator<char> >::filter(char const*&, char const*, char*&, char*, bool)':
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x3d): undefined reference to `boost::iostreams::detail::lzma_base::before(char const*&, char const*, char*&, char*)'
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x4e): undefined reference to `boost::iostreams::lzma::finish'
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x59): undefined reference to `boost::iostreams::lzma::run'
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x65): undefined reference to `boost::iostreams::detail::lzma_base::deflate(int)'
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x81): undefined reference to `boost::iostreams::detail::lzma_base::after(char const*&, char*&, bool)'
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x8b): undefined reference to `boost::iostreams::lzma_error::check(int)'
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x92): undefined reference to `boost::iostreams::lzma::stream_end'
libbleualign_cpp_lib.a(CompressedWriter.cpp.o): In function `boost::iostreams::detail::lzma_compressor_impl<std::allocator<char> >::close()':
CompressedWriter.cpp:(.text._ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE5closeEv[_ZN5boost9iostreams6detail20lzma_compressor_implISaIcEE5closeEv]+0x1e): undefined reference to `boost::iostreams::detail::lzma_base::reset(bool, bool)'
collect2: error: ld returned 1 exit status
CMakeFiles/bleualign_cpp.dir/build.make:102: recipe for target 'bleualign_cpp' failed
make[2]: *** [bleualign_cpp] Error 1
CMakeFiles/Makefile2:73: recipe for target 'CMakeFiles/bleualign_cpp.dir/all' failed
make[1]: *** [CMakeFiles/bleualign_cpp.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas of what may be wrong?

**Comment by hieuhoang** [comment]
balls. The boost library that is installed by ubuntu doesn't include lzma compression.

THink it's worth the pain of a custom boost installlation?

**Comment by hieuhoang** [comment]
I think it's worth it - xz files are 33% the size of gz file.

Committed code to create nodes that supports it
   https://github.com/bitextor/bitextor/commit/c019c27ad9f1ac599ccd785458644ca67a3b2c4d

On an existing machine:
   sudo apt-get remove libboost-all-dev
   sudo apt-get remove

        wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz
        tar xvf boost_1_66_0.tar.gz
        cd boost_1_66_0/
        ./bootstrap.sh
        ./b2 -j16 --layout=system  install || echo FAILURE
        cd ..
        rm -rf boost_1_66_0*

**Comment by mespla** [comment]
This worked smoothly, thanks!

**Comment by hieuhoang** [comment]
Changed my mind. The xz files created by bleualign-cpp are insignicant compared to the overall disk usage (162MB v. 24GB+). Gonna use gz instead and install boost from ubuntu package

**Comment by hieuhoang** [comment]
done
