### ISSUE TITLE
tt2ttmime output error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#43]
On a few of the urls, snakemake is outputs corrupted binary files, rather than text ttmime. An example input is http://statmt.org/hieu/downloads/tt2ttmime/wn.tt

**Comment by hieuhoang** [comment]
errr. can you add file extension so i know that it is, and what compression

**Comment by hieuhoang** [comment]
are you sure this kind of command works?
           'zcat -f | {BITEXTOR}/bitextor-identifyMIME.py | gzip < {input} > {output}'
shouldn't it be 
        'zcat -f {input} | {BITEXTOR}/bitextor-identifyMIME.py | gzip -c > {output}'
?

**Comment by lpla** [comment]
You are right, my mistake. I will fix it ASAP

**Comment by lpla** [comment]
Could you test it now? I can’t as it seems like I have missing new config variables.

**Comment by hieuhoang** [comment]
cheers. had to zip a few more files to make it work
   https://github.com/bitextor/bitextor/commit/978c39f868174fcaca705c61e2b853e0b98e89d7
look into my config file to see what variables you're missing. Can't remember if i've added more

**Comment by lpla** [comment]
Great! Thanks!

**Comment by hieuhoang** [comment]
is there a reason .tt isn't zipped?

**Comment by hieuhoang** [comment]
in xtt2boiler, why "  cat {input} > {output}; " and not "  ln -s {input}  {output}; "
?

**Comment by hieuhoang** [comment]
any chance of changing gzip -> xz. It takes longer but it looks like it's 1/3 to 1/6 of the size. Which is a lot

**Comment by lpla** [comment]
I made .tt compressed, added some symlinks on some " cat {input} > {output}" and 'cp {input} {output}" commands and changed gzip with xz. Tell me if anything goes wrong.

**Comment by hieuhoang** [comment]
excellent. I'll test it later. Have a utf8 problem i'm trying to tackle

**Comment by lpla** [comment]
I think I fixed the utf8 problem now.

**Comment by hieuhoang** [comment]
all cool so far. Small en-fr crawl that took 400GB in the transient dir now take 20GB. No utf8 error yet
