### ISSUE TITLE
document aligner project

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#45]
Now that marek's document aligner code is in bitextor, can someone kill of the separate project, or at least make it read-only to avoid any confusion
   https://github.com/paracrawl/document-aligner/issues

**Comment by lpla** [comment]
Only @bhaddow , @kpu and @marekstrelec can delete repositories in Paracrawl organisation (they are owners, everybody else there are members).

**Comment by lpla** [comment]
Replaced the submodule with its content in master branch.

Please, @bhaddow or @kpu, delete the repository, we are ready.

Also, would it be possible to reference Bitextor project in Paracrawl organisation page here in Github? (https://github.com/paracrawl) The code hosted there is not longer used. Or at least, change the Github link we have in paracrawl.eu homepage (above the pipeline diagram) to link Bitextor organisation or repo .

**Comment by kpu** [comment]
Done
