### ISSUE TITLE
Post-pipeline tasks

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#46]
It looks like the pipeline is complete. Yay!!! The BLEU scores don't look good for my realistic en-so run so I'm checking the steps again. 

Would like to start thinking what we should do to make things better. Feel free to add your own

1. Non-NLTK tokenizer. I'll be making sure that the marek aligners can have other tokenizers. Alicante should ensure that their existing tools can use other tokenizers/detoks.
2. Add SMT. For BLEU score comparison. For use in marek's aligners
3. Make NMT rules more general. At the moment, it is hardcoded to use RNN/GRU in Marian. Encourage other people to use the NMT Snakemake file

**Comment by hieuhoang** [comment]
4. Add bicleaner training
5. Add training for bitextor's document and sentence aligner. (Just create dictionary?)

**Comment by hieuhoang** [comment]
6. Give slurm job descriptivve names. At the moment, they are all 'snakejob' which makes it difficult to identify and kill indivdual jobs
7. Allow and test different html->text methods. Tests different variations of the entire pipeline, eg. httrack v. creepy, nmt v. smt, marek aligners v. bitextor aligners

**Comment by mespla** [comment]
8. Convert doc_align.sh and bleualign.sh to Snakemake rules
9. Add deduplication before bicleaner
10. Add documentation for all options (also some guides to developers that
want to contribute to the project)

Missatge de Hieu Hoang <notifications@github.com> del dia dv., 23 de nov.
2018 a les 13:20:

**Comment by lpla** [comment]
FYI, we are managing our tasks on the "Projects" tab of Github: https://github.com/bitextor/bitextor/projects/1

That would help us to know what tasks have priority and who is doing them

**Comment by hieuhoang** [comment]
11. Use requirements.txt in slurm/install.sh. Art the moment, they both have separate lists of python requirements. Both need to correct and up to date

**Comment by lpla** [comment]
I added all tasks from last meeting and this issue to the Bitextor 7.0 Cycle "Projects" table: https://github.com/bitextor/bitextor/projects/1

Let's continue managing our tasks there, please.
