### ISSUE TITLE
JY_about_regex_problem_in_bitextor_script

### ISSUE THREAD

**Issue by JiaYueHuang** [bitextor/bitextor#50]
In the align_documents_and_segments() function of the bitextor script, I found that the regex expression in the following has some problem(is it the '\s' should be replaced by '\S' ？, which match the non-null characters):
tail -n +2 $VOCABULARY | sed -r 's/^([^\s]+)\t([^\s]+)$/\2 @ \1/g' > $HUNALIGN_DIC

**Comment by JiaYueHuang** [comment]
Thanks for your reply. 
Today I did an experiment on the sample dictionary (en-ca.dic)
I wrote a bash script to detect the following two regex expression, and then I found  a problem described in the following():
tail -n +2 en-ca.dic | sed -r 's/^([^\s]+)\t([^\s]+)$/\2 @ \1/g' > output_s
tail -n +2 en-ca.dic | sed -r 's/^([^\S]+)\t([^\S]+)$/\2 @ \1/g' > output_S

the bash script described as follow (regex_test.sh):
TEST_DIC_NAME=en-ca.dic
tail -n +2 ${TEST_DIC_NAME} | sed -r 's/^([^\S]+)\t([^\S]+)$/\2 @ \1/g' > S_out_${TEST_DIC_NAME}
tail -n +2 ${TEST_DIC_NAME} | sed -r 's/^([^\s]+)\t([^\s]+)$/\2 @ \1/g' > s_out_${TEST_DIC_NAME}
echo "===================================="
echo "the total lines of the dictionary:"
wc -l ${TEST_DIC_NAME}
echo "===================================="
echo "the  s_out_${TEST_DIC_NAME}  result:"
echo "total  lines  containing the  @  character:"
grep @ s_out_${TEST_DIC_NAME} | wc -l
echo "total  lines not containing the  @  character:"
grep -v @ s_out_${TEST_DIC_NAME} | wc -l
echo "===================================="
echo "the  S_out_${TEST_DIC_NAME}  result:"
echo "total  lines  containing the  @  character:"
grep @ S_out_${TEST_DIC_NAME} | wc -l
echo "total  lines not containing the  @  character:"
grep -v @ S_out_${TEST_DIC_NAME} | wc -l


Do the above test, and I found that using the following may have better result:
 "tail -n +2 en-ca.dic | sed -r 's/^([^\S]+)\t([^\S]+)$/\2 @ \1/g' > output_S "
But I don't konw the reason.

**Comment by mespla** [comment]
Hi,

I have reproduced your experiment and you are right. I don't understand why
this happens, since \s should represent a blank space and \S should
represent anything that is not a blank space. So, to make sure that the
regular expression does what it should do, I replaced \s with [:space:].
Now it should work properly.

Best,

Miquel.



Missatge de JY <notifications@github.com> del dia dc., 5 de des. 2018 a les
14:40:

**Comment by mespla** [comment]
This is definitely a weird behaveour of sed. Give a try to the awk command:
awk 'begin {fs=ofs="\t"} {print $2, "@", $1}'

I replaced in bitextor.sh at the master at it seems to work correctly both
with your dictionary and the ones I already had.

Missatge de JY <notifications@github.com> del dia dc., 5 de des. 2018 a les
15:26:

**Comment by lpla** [comment]
This is now integrated in `master`and `6.x` series branch. Release 6.0.1 incoming. If you find anything else wrong with this new expression, please, reopen the issue. Thanks for all your feedback!
