### ISSUE TITLE
JY_some_problem_in_script_bitextor-lett2lettr

### ISSUE THREAD

**Issue by JiaYueHuang** [bitextor/bitextor#51]
In the script bitextor-lett2lettr, the handle_data( self, data ) function of the class Parser(html.parser.HTMLParser) is not for common purpose? Because the logic of this function split the contents by "  "(space charater), but in some language, the words of the contents doesn't split by "  ", such as Chinese, which has no "  " between the contents.

**Comment by mespla** [comment]
Hi!

You are right, we should run tokenisation here. We are working to replace
all the calls to tokenization in the code so the user can specify a custom
tokenizer that is passed as an argument when each script is called. We will
have an eye on this to do the same.

Miquel.

Missatge de JY <notifications@github.com> del dia dc., 5 de des. 2018 a les
8:18:

**Comment by lpla** [comment]
Feature merged into master with new pipeline. Closing.
