### ISSUE TITLE
bitextor-identifyMIME.py error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#52]
# cat 1  | ~/permanent/software/bitextor/bitextor-identifyMIME.py
Traceback (most recent call last):
  File "/home/hieu/permanent/software/bitextor/bitextor-identifyMIME.py", line 41, in <module>
    magicoutput.append(base64.b64encode(base64.b64decode(content + "==").decode(magicoutput[1].split("=")[1].replace("unknown-8bit","iso-8859-1").replace('us-ascii','iso-8859-1')).encode("utf8")).decode("utf8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 16161: invalid continuation byte
[1.gz](https://github.com/bitextor/bitextor/files/2651075/1.gz)

**Comment by hieuhoang** [comment]
For now, I've hacked the script to write 'dunno' to the output stream when there is an encoding error
   https://github.com/bitextor/bitextor/commit/0396e2457d755c75f1de1860fab5e37cabed285a

**Comment by mespla** [comment]
I have added a second attempt to convert the file by using ISO-8859-1 by default. Should we better discard a file if te encoding cannot be identified properly? This is, insetad of printing it with dunno, just not including it in the ouptut of the script?
