### ISSUE TITLE
compile error on bitextor-malign

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#54]
%  ./autogen.sh
 %  ./configure 
...
config.status: error: cannot find input file: `Makefile.in'

**Comment by hieuhoang** [comment]
actually, autogen.sh has the error
./autogen.sh
- aclocal.
- autoconf.
- autoheader.
- automake.
configure.ac:516: error: required file 'zipporah/Makefile.in' not found

**Comment by lpla** [comment]
Ok, I am testing that

**Comment by hieuhoang** [comment]
it seems like zipporash doesn't have a makefile.am

**Comment by lpla** [comment]
Try now. But Zipporah is deleted in `bitextor-malign` branch, so I don't know why you are having this error. A clean clone of the branch compiles without any issue for me.

**Comment by hieuhoang** [comment]
hmm. I dont know how you test it. Didn't work for me until this change
   https://github.com/bitextor/bitextor/commit/191d99a835bedbe5dd058da01a6488e725b7f963

**Comment by lpla** [comment]
You are right. `git` left the Zipporah folder from master in my installation. Your change is correct, thanks!
