### ISSUE TITLE
Error in rule mkcls:

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#55]
#   /home/hieu/permanent/software/bitextor/bin/mkcls -c50 -n2 -p/tmp/transient/tempcorpuspreproc.fr-en/corpus.clean.fr -V/tmp/transient/tempgizamodel.fr-en/corpus.fr.vcb.classes opt 

/home/hieu/permanent/software/bitextor/bin/mkcls: 1: eval: /home/hieu/permanent/software/bitextor/bin/clustercat: not found

**Comment by hieuhoang** [comment]
problem - clustercat not compiled when make is run

**Comment by mespla** [comment]
Fixed,

I don't know why it seems that there was not a rule to compile clustercat
in Makefile.am. Now it is in place.

Miquel.

Missatge de Hieu Hoang <notifications@github.com> del dia dt., 11 de des.
2018 a les 16:20:

**Comment by hieuhoang** [comment]
ta https://github.com/bitextor/bitextor/commit/f17907b9867176e38ec3ffae6c9a3820fc724497
