### ISSUE TITLE
bicleaner training

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#56]
it looks like bicleaner training is in snakemake now. Can you please provide the yaml file that goes with the example snakemake config
   https://github.com/bitextor/bitextor/blob/1512559650df9f859eda1df037147686c3f3fd0f/snakemake/example/config.fr-en.dics.json#L20

**Comment by mespla** [comment]
No, it is not yet, it will be soon. That is the option to apply an existing
model such as those in https://github.com/bitextor/bitextor-data

Miquel.

Missatge de Hieu Hoang <notifications@github.com> del dia dt., 11 de des.
2018 a les 16:29:

**Comment by hieuhoang** [comment]
ah ok. ta
