### ISSUE TITLE
bitextor: command not found

### ISSUE THREAD

**Issue by mzeidhassan** [bitextor/bitextor#57]
Hi all,

I have been trying to install bitextor on a couple of virtual machines, but I keep getting this error after completing all steps. I have installed bitextor before a couple of times, and didn't have any issue. I am using Ubuntu 16.04 and the bitextor command is not recognized for some reason. Any idea how to fix this?

If I run "./bitextor.sh", I see the help of Bitextor, but nothing else works. This command won't work for example

./bitextor.sh -u http://www.dlsi.ua.es/~mespla -v en-ca.dic -x en ca

It displays the help instructions again.

Thanks

**Comment by lpla** [comment]
Could you paste the error lines before the help lines `USAGE: bitextor [OPTIONS] -u URL -e FILE [-v VOCABULARY] LANG1 LANG2...`?

**Comment by mzeidhassan** [comment]
Hi @lpla, 

Thanks for your follow-up. After downloading the en-ca.dic in the same directory, I got the following error after running the above command.
`./bitextor.sh: line 287: ./bitextor-ett2lett: No such file or directory
./bitextor.sh: line 424: ./bitextor-lett2lettr: No such file or directory
./bitextor.sh: line 425: ./bitextor-lett2idx: No such file or directory
./bitextor.sh: line 446: ./bitextor-structuredistance: No such file or directory
./bitextor.sh: line 447: ./bitextor-urlsdistance: No such file or directory
./bitextor.sh: line 448: ./bitextor-mutuallylinked: No such file or directory
./bitextor.sh: line 449: ./bitextor-urlscomparison: No such file or directory
./bitextor.sh: line 444: ./bitextor-idx2ridx: No such file or directory
./bitextor.sh: line 439: ./bitextor-urlsetoverlap: No such file or directory
./bitextor.sh: line 445: ./bitextor-imagesetoverlap: No such file or directory
./bitextor.sh: line 450: ./bitextor-urlsetoverlap: No such file or directory
./bitextor.sh: line 436: ./bitextor-urlsdistance: No such file or directory
./bitextor.sh: line 437: ./bitextor-mutuallylinked: No such file or directory
./bitextor.sh: line 438: ./bitextor-urlscomparison: No such file or directory
./bitextor.sh: line 435: ./bitextor-structuredistance: No such file or directory
./bitextor.sh: line 434: ./bitextor-imagesetoverlap: No such file or directory
./bitextor.sh: line 433: ./bitextor-idx2ridx: No such file or directory
./bitextor.sh: line 440: ./bitextor-rank: No such file or directory
./bitextor.sh: line 451: ./bitextor-rank: No such file or directory
./bitextor.sh: line 375: ./bitextor-buildTMX: No such file or directory
./bitextor.sh: line 474: ./bitextor-align-documents: No such file or directory
./bitextor.sh: line 362: ./bitextor-elrc-filtering: No such file or directory
`

**Comment by lpla** [comment]
Are you using `master` branch code or release 6.X code?

**Comment by mzeidhassan** [comment]
I used this command "git clone --recurse-submodules https://github.com/bitextor/bitextor.git"

**Comment by mzeidhassan** [comment]
OK, it's working now. So, I did git clone https://github.com/bitextor/bitextor.git, then git submodule update --init --recursive. After that, I used all other commands. I think the installation wiki can be improved a bit and made it clearer. Thanks @lpla ! Your follow-up helped me resolve the issue eventually. For some reason, I thought "git clone --recurse-submodules https://github.com/bitextor/bitextor.git" would take care of everything, but apparently it didn't.

**Comment by lpla** [comment]
Good to know! If you have any other issue, try first with a released version (now the 6.0.1), because `master` could have some features broken sometimes.

Regarding installation process, it will be easier in the next cycle (Bitextor 7.0) as we redesigned the main script and dependences.

**Comment by mzeidhassan** [comment]
Thanks for the advice and look forward to release 7.0. Any rough date when it will be available?

**Comment by lpla** [comment]
We expect to release it around March 2019, at the end of Paracrawl project.

**Comment by mzeidhassan** [comment]
This is great news! Thanks @lpla ! I am closing this issue now. I appreciate your help.
