### ISSUE TITLE
Error in docaling_matches

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#58]
rule docaling_matches:
    input: /home/hieu/transient/so-en.large/heemaalnews.docalign/so.marek-smt.extracted.translated.xz, /home/hieu/transient/so-en.large/heemaalnews.docalign/en.extracted.xz
    output: /home/hieu/transient/so-en.large/heemaalnews.docalign/so-en.marek-smt.matches
    jobid: 0
    wildcards: dir=/home/hieu/transient/so-en.large/heemaalnews.docalign, mttype=marek-smt

Traceback (most recent call last):
  File "/home/hieu/permanent/software/bitextor/document-aligner/compute_matches.py", line 12, in <module>
    from scorer import CosineDistanceScorer, WordExtractor, _ngram_helper
  File "/home/hieu/permanent/software/bitextor/document-aligner/scorer.py", line 12, in <module>
    from external_processor import ExternalTextProcessor
ModuleNotFoundError: No module named 'external_processor'
[Thu Dec 13 04:50:06 2018]
Error in rule docaling_matches:
    jobid: 0
    output: /home/hieu/transient/so-en.large/heemaalnews.docalign/so-en.marek-smt.matches

**Comment by lpla** [comment]
Sorry! I forgot to commit some files for generic tokeniser. Please, pull all changes, update submodules and try again.

**Comment by hieuhoang** [comment]
cheers. I'm gonna change word-tokeniser1 to LANG1Tokenizer. LANG1Tokenizer has already been defined and variables with '-' can't be passed on the command line eg https://github.com/bitextor/bitextor/blob/bdcc0094c19d7f8087ebc3b399073eb67a731d1a/snakemake/Snakefile#L546

Why are you making multiple copies of external_processor.py, rather than referring to 1 copy?

**Comment by hieuhoang** [comment]
And can you check in nltk-word-tokeniser.py

**Comment by lpla** [comment]
This is my tokeniser example script. Any executable that expects stdin and
prints tokenised output using stdout would work, both word tokeniser and
sentence tokeniser/splitter parameters. If you need it, I could add it to
the example folder.

**Comment by hieuhoang** [comment]
ok, wherever

**Comment by lpla** [comment]
Added!

**Comment by hieuhoang** [comment]
cheers. All running!
