### ISSUE TITLE
piped-boilerpipe is removing spaces from some Gujarati text

### ISSUE THREAD

**Issue by bhaddow** [bitextor/bitextor#60]
I have this site (https://ahmedabad.gujarat.gov.in/permission-festival-booking-rules-form-50) encoded as an xtt file (see http://www.statmt.org/bhaddow/xtt). When I run it through piped-boilerpipe, eg
```
cat xtt | java -Dfile.encoding=UTF-8 -jar ~/code/bitextor/install-u18-malign/share/java/piped-boilerpipe.jar | cut -f 5 | base64 -d
```
all the spaces are removed from the Gujarati text. I think this is happening in the HTMLhighlighter.

If I go to https://boilerpipe-web.appspot.com/ and paste in the URL, it appears to work fine. 

If this is a problem in boilerpipe, there may not be much we can do, but workarounds are appreciated. Can we just use the text straight out of ArticleExtractor? This looks fine.

**Comment by bhaddow** [comment]
Actually the problem is related to bitextor-get-html-text.py

In Hieu's pipeline, the ttmime file is converted to an xtt file, with the addition of a fifth field by bitextor-get-html-text.py. This (amongst other things) changes the Gujarati utf8 characters to html elements like "&#2726;&#2765;&#2732;&#2750;&#2736;&#2750; &#2709;&#2750;&#2736;&#2765;&#2735;&#2709;&#2765;&#2736;&#2734;". The spaces are still in, and this html displays correctly. However the HTMLhighlighter in boilerpipe does not handle it correctly. If I change PipedBoilerpipe so that it gets the html from field 3 (instead of 4), it process the Gujarati correctly.

**Comment by lpla** [comment]
Fixed in commit https://github.com/bitextor/bitextor/commit/1807daf89fd7f82ca676648a251222f25cd9b0de

Code available in master and next release this week.

Closing
