### ISSUE TITLE
boilerplate removal

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#61]
is it still possible to run the boilerplate removal? I get a error when i tried to run it
   java -Dfile.encoding=UTF-8 -jar /home/hieu/permanent/software/bitextor/piped-boilerpipe/piped-boilerpipe.jar
Error: Unable to initialize main class pipedboilerpipe.PipedBoilerpipe
Caused by: java.lang.NoClassDefFoundError: de/l3s/boilerpipe/BoilerpipeProcessingException

Same problem even if i run install
  ./configure  --prefix=$PWD
  make -j
  make install

**Comment by lpla** [comment]
That's weird. That java command works for me. Are you using latest code? Did you try to run "make clean" before the installation?

**Comment by hieuhoang** [comment]
ah yes. All working now. Some tweaks https://github.com/bitextor/bitextor/commit/464f8abcd3f08e910c49aac511285093f752bfc2
