### ISSUE TITLE
bitextor-get-html-text error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#63]
# cat 1 | /home/hieu/permanent/software/bitextor/bitextor-get-html-text.py -t
Traceback (most recent call last):
  File "/home/hieu/permanent/software/bitextor/bitextor-get-html-text.py", line 72, in <module>
    soup = BeautifulSoup(base64.b64decode(fields[3]).decode("utf-8"), "lxml", from_encoding='utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 3: invalid start byte

[1.gz](https://github.com/bitextor/bitextor/files/2698259/1.gz)

**Comment by mespla** [comment]
There seems to be something weird in the input file: according to the
piipeline, it should contain the following tab-separated fields:
mime_type \t encoding \t url \t base64_encoded_html

In the file you are using for testing, it seems that HTML is not base64
decoded.

Missatge de Hieu Hoang <notifications@github.com> del dia dj., 20 de des.
2018 a les 10:49:

**Comment by hieuhoang** [comment]
it was process with the boilerplate remover. Moving to hu-en now so not retesting this. Will re-open if it re-occurs
