### ISSUE TITLE
func_timeout error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#64]
snakemake --snakefile ../Snakefile --cores 2222 -j 2222 -k --configfile config.so-en.large.json --cluster "sbatch {cluster.gres}" --cluster-config ../cluster.json  
ModuleNotFoundError in line 14 of /home/hieu/permanent/software/bitextor/snakemake/Snakefile:
No module named 'func_timeout'
  File "/home/hieu/permanent/software/bitextor/snakemake/Snakefile", line 14, in <module>

**Comment by hieuhoang** [comment]
ah, need to do pip3 install

**Comment by hieuhoang** [comment]
good reason why slurm/install.sh and requirements.txt should be tied together

**Comment by lpla** [comment]
I think that now slurm/install.sh is in sync with requirements.txt. Tell me if next time you use it you have any issues (I am not further testing it to avoid spending more Azure credit)

**Comment by hieuhoang** [comment]
cooilio
