### ISSUE TITLE
uri encoding error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#65]
$ echo một-số-dữ-liệu-từ-thiết-bị-trước-đây-của-tôi-không-có-trên-thiết-bị-m�index.6e32 | $BITEXTOR/bitextor-dir2warc.py
File "/home/hieu/permanent/software/bitextor/bitextor-dir2warc.py", line 37, in <module>
    warc_record = warc.WARCRecord(payload=content,headers={"WARC-Target-URI":url.decode("utf8"),"WARC-Date":dvalue})
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 228-229: invalid continuation byte
 I've hacked a fix https://github.com/bitextor/bitextor/commit/6ee504a76f103deb824e19cc3ff72ed414fc9975.

Not sure the best way to fix it, and what the uri encoding should be. Maybe change the encoding of the filename, but that requires changing httrack

**Comment by mespla** [comment]
I'd like to reproduce the error. What is the URL you've been crawling from?
