### ISSUE TITLE
Computational requirements document

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#70]
ParaCrawl 1 promised a computational resource requirements document.  

We sort of have one in the README https://github.com/bitextor/bitextor but indicative CPU, RAM, disk space for a few languages would help.

**Comment by lpla** [comment]
Uploaded here: https://github.com/bitextor/bitextor/blob/master/technical_requirements.md

Please, report any mistake or missing information for Bitextor 7.0/Paracrawl release.

**Comment by kpu** [comment]
Um, it completely understates computational requirements for e.g. providing a Czech corpus?

**Comment by kpu** [comment]
Job scheduler?

**Comment by mespla** [comment]
> Um, it completely understates computational requirements for e.g. providing a Czech corpus?
> Job scheduler?

I have added a new section describing the use case for EN-HU in Paracrawl2 project and reduced the explanation about the minimum requirements. I am waiting for crawling details, but it is almost done.
