### ISSUE TITLE
The big problems  in bitextor-structuredistance script

### ISSUE THREAD

**Issue by JiaYueHuang** [bitextor/bitextor#72]
This script can not ensure that the same label in two different html strings be replaced by the same character.   This may influence the calculation of editDinstance seriously. 
e.g.  two html strings are as follows：
string1:   "_html_____body___lable___lable___p__p__body__html_" 
string2:   "_html_____body___p__p____lable___lable__body__html_"

In this case, the 'p' of the string1 and the 'p' of the string2 would be transformed to different character(It should be not).

**Comment by lpla** [comment]
You are right. It will happen with single character tags, like <i>, <b>, <p>, etc. We expect to rewrite this script and re-train our logistic regression model for Bitextor 7.0 release.

**Comment by JiaYueHuang** [comment]
[bitextor-structuredistance.txt](https://github.com/bitextor/bitextor/files/2755726/bitextor-structuredistance.txt)

**Comment by lpla** [comment]
> [bitextor-structuredistance.txt](https://github.com/bitextor/bitextor/files/2755726/bitextor-structuredistance.txt)

If this is a code change, please, create a Pull Request to review it properly.

**Comment by lpla** [comment]
We fixed this in commit 7c6f62053e43a216a93d4ab8e1b85385d50745a7. Please, reopen this issue if necessary and thanks for your report!
