### ISSUE TITLE
Issue with the Arabic collected result 

### ISSUE THREAD

**Issue by iyadahmad** [bitextor/bitextor#73]
Hello again ,

Bitextor is working properly . But we've got an issue with result : 

The Arabic words appears without spaces and those spaces needed to make the text readable. why is that happening ? also we've tried MLTERM to make sure that the ubuntu terminal support Ararbic but the same result as well.

<tu tuid="1" datatype="Text"><prop type="type">1:1</prop><tuv xml:lang="en"><prop type="source-document">https://FILTEREDSITE.com/sa-en/xiaomistore/p/?ref=nav</prop><seg>**All orders of 200.00 SAR or more on eligible items across any product category qualify for FREE Shipping**.</seg></tuv><tuv xml:lang="ar"><prop type="source-document">https://FILTEREDSITE.com/sa-ar/messenger-bags/%D8%AD%D9%82%D8%A7%D8%A6%D8%A8-%D9%8A%D8%AF-472/%D8%B1%D8%AC%D8%A7%D9%84/a-t-106356/s/?page=1</prop><seg>**احصلعلىشحنمجانيعندشراءكسلعمشمولةفيالشحنالمجانيبقيمة** **200.00 ريـالاواكثر**.</seg></tuv></tu>

Any help would be greatly appreciated.

Best regards

**Comment by lpla** [comment]
This is duplicated/related to issue #67. We are working on it.

**Comment by lpla** [comment]
Are you using Bitextor 6.0 versions or master branch code?

**Comment by lpla** [comment]
I am unable to reproduce the problem, as I recently said in #67 . I crawled the same domain as you (24 hours and I stopped the process), and the result has correctly separated words, using spaces. I am reading the output file with `less` and `vim`. Maybe it is related with your TMX/tab separated files reader. Which are you using @iyadahmad ?

I used master branch, in a vanilla install of Ubuntu 18.04 (English language), creating dictionaries from OpenSubtitles2018 (OPUS) for pair en-ar. Could you also check that this issue happens to all output lines and not only some of them? Or give me more examples or any other information about your system or environment?

**Comment by lpla** [comment]
Just one more thing. Could you try to run the same command line adding `-B` option? I suspect this is the root of the issue.

**Comment by iyadahmad** [comment]
Thank you! -B option worked perfectly :+1:

**Comment by iyadahmad** [comment]
> I am unable to reproduce the problem, as I recently said in #67 . I crawled the same domain as you (24 hours and I stopped the process), and the result has correctly separated words, using spaces. I am reading the output file with `less` and `vim`. Maybe it is related with your TMX/tab separated files reader. Which are you using @iyadahmad ?
> 
> I used master branch, in a vanilla install of Ubuntu 18.04 (English language), creating dictionaries from OpenSubtitles2018 (OPUS) for pair en-ar. Could you also check that this issue happens to all output lines and not only some of them? Or give me more examples or any other information about your system or environment?

Can you share the en-ar dictionary you created

**Comment by lpla** [comment]
Uploaded at https://github.com/bitextor/bitextor-data/tree/master/dics
