### ISSUE TITLE
recursive definition in requirements

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#74]
I've deleted bicleaner's requirement in the bitextor requitements.txt
   https://github.com/bitextor/bitextor/commit/2e25fd44131d27fe1fb92cde0e01059b5ff78899
'cos it doesn't work when running slurm install
   https://github.com/bitextor/bitextor/blob/c69a59e772b0ac876fd6b73f4cab247a14411bb0/slurm/install.sh#L38

There's probably several ways to fix it, the choice is yours. We can do it together

**Comment by lpla** [comment]
You are right. I did it to simplify the installation commands in README.md, but I didn't see the cons of using a path for another requirements.txt file. More if path is relative and you move it, which happens in the SLURM installation.

So don't worry. I will simply change the README.md 'installation' chapter with this command:

`sudo pip3 install -r requirements.txt -r bicleaner/requirements.txt`

Thanks for your report!
