### ISSUE TITLE
Important content is ignored

### ISSUE THREAD

**Issue by iyadahmad** [bitextor/bitextor#75]
I used the below command to generate t1.xml file
bitextor -B -u THE_URL -v en-ar.dic -x en ar > t1.xml

The file has been generated successfully however not all the content was extracted, actually the most important content hasn't been added to the file. Is there a limitation for the tags hierarchy? 

Regards,

**Comment by mespla** [comment]
The problem may come from many places:
* the page may not be downloaded,
* language identification could be wrong, 
* the tool may fail to identify the translation of the document you are looking for (it may not exist, in fact),
* the segment/s you are looking for could be not aligned properly, etc.
It is hard to say what is wrong without knowing the URL or the content that is ignored. 

I would suggest to run bitextor with option `-I <PATH>` to store the intermediate files of each step of the pipeline in `<PATH>` so you can try to identify where the piece of information you are looking for desapears.

Good luck! Regards,

**Comment by iyadahmad** [comment]
When running with -I option, I receive the following message:
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fd6f7addbe0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/c_api_util.py", line 30, in __init__
TypeError: 'NoneType' object is not callable

Am I missing something here?

Thank you!

**Comment by lpla** [comment]
Could you try with new release version code? (master branch)

> I used the below command to generate t1.xml file
> bitextor -B -u THE_URL -v en-ar.dic -x en ar > t1.xml
> 
> The file has been generated successfully however not all the content was extracted, actually the most important content hasn't been added to the file. Is there a limitation for the tags hierarchy?
> 
> Regards,

**Comment by lpla** [comment]
It's been 5 month since last activity in this issue and its topic is too abroad. Please, reopen it if necessary.
