### ISSUE TITLE
inconsistent cleanHTML string on Ubuntu 16.04

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#77]
ONLY on Ubuntu 16.04 (not 18.04), running this repeatedly on the same warc file give different md5 hash each time:
   xzcat www.samsonite.be.xz | $BITEXTOR/bitextor-warc2preprocess.py --output-dir out --lang1 en --lang2 fr

**1s run:**
  hash 97d16515e455bd253629e02a5f6f6333 unknown
hash f837f16aa9335a6982ca6b3288c986e6 unknown
hash 06335a660e3f24a40e675d886a90d1c3 unknown
hash f3db00f4f4a5b7261fb20719f065ae25 unknown
hash f6aab667d5b48e1b1964c6ea6f95e267 unknown
hash 53abca46b44e84a72ffaafeeae1e9d30 unknown
hash 244acb0e594df46be28db0fb58fb3536 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=SAMS080&scrollTo=%2523product-reviews
hash 2efd7b0a965df733ac305d9fa0807458 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=8636&scrollTo=%23product-reviews
hash 08b2a5c512a1e053dc682d72647ad45e www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=SAMS312
hash 68453ddc4670716b49bf7becd67a8e6e www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=8636
hash 9067beffeffd407bba5a9f3030fed066 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html

**2nd run:**
hash aac227d8559fef0cd5389b062a7712d8 unknown
hash a41a744d948e80215efdf8609ed7f9f9 unknown
hash 5c8a7fd314a221788d8981ae18cf5608 unknown
hash 88fcdee0d114df983e2ebdb7f57511d3 unknown
hash 8b1410305f36c1fd9f2d885651a293e8 unknown
hash 31f94878704e9e3a61fc0f0f6db37705 unknown
hash 1dababad273cca9cfb8c5ff5c24d6f16 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=SAMS080&scrollTo=%2523product-reviews
hash c5ae0c8edf79221691e1fc58f910938a www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=8636&scrollTo=%23product-reviews
hash ad4531aa164e228004cd100c745ebe1b www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=SAMS312
hash 08ca1ab4f0a82372dd8062a192eed9c9 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=8636
hash 50c95c18970412c3e7915de27c244967 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html
^Chash 846ab962f4b0e8f22f586077f7af4715 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=SAMS080&scrollTo=%23product-reviews

By contrast, Ubuntu 18.04 gives this consistently
hash ff1f5bc1b15ad0fa15ef5db9396d8988 unknown
hash dbaf4dfd39d153f92e256f3f9bb64dbb unknown
hash 68f39de77eddc3c9c234c7910cc10f11 unknown
hash 8b96043896a91d39eb11ba18d22623df unknown
hash cd4909e5eb2a1a58ae078cebafcea19c unknown
hash 9984901d003f6202516374ae66ab4190 unknown
hash 4ccae89e12b439d660f5239630a47925 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=SAMS080&scrollTo=%2523product-reviews
hash da2b1faf7140e17ca0ad685f43b4cb28 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=8636&scrollTo=%23product-reviews
hash 7bb751be8645216d201c4eb4c5394e48 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=SAMS312
hash aa8effc49d6fa67ce41fac9b89ce7de8 www.samsonite.be/fr/pro-dlx-5-spinner-expandable-55cm--oxford-blue/106371-1647.html?cgid=8636

Warc file here
   http://statmt.org/hieu/paracrawl/www.samsonite.be.xz

**Comment by hieuhoang** [comment]
it looks like it's from this line
   cleantree = cleantree.replace("\t", " ")

**Comment by hieuhoang** [comment]
it looks like it's from this command on line 95
    cleantree = tree.decode("utf8")

**Comment by hieuhoang** [comment]
oh dear, the order of the html attributes are inconsistent, eg
run1: <div id="engraving-65754" class="engraving-content customEngravementText engraving-product-65754-4386">
run2:<div class="engraving-content customEngravementText engraving-product-65754-4386" id="engraving-65754">

unless we make it consistent, the code won't work on Ubuntu 16.04

**Comment by mespla** [comment]
That's weird... so you get inconsistent attribute order when running on the same WARC file twice on the same machine? Is attribute order consistent in the same run? If so, deduplicacion should be working properly despite this fact. If you have some sample I can reproduce, I use Ubuntu 16.04 on my computer and I could help to find a solution.

**Comment by hieuhoang** [comment]
i think you're right, it gives the same has in the same run.
   xzcat s.warc.xz | $BITEXTOR/bitextor-warc2preprocess.py --output-dir out --lang1 en --lang2 fr
scary
