### ISSUE TITLE
-I option gives an exception

### ISSUE THREAD

**Issue by iyadahmad** [bitextor/bitextor#78]
When I add the -I option, I receive the below exception:

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f9c779d2f28>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/c_api_util.py", line 30, in __init__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f445b11cba8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable

Let me know if I miss anything here.

Thank you!

**Comment by iyadahmad** [comment]
Upgrade worked fine. But still not all the segments exists, just the header and the footer.
I tried with -I option and the segments exists in the crawl file but not in the aligned segments in the XML!
Your help is highly appreciated.

Regards,

**Comment by lpla** [comment]
Between crawl file and output there are lots of steps (explained in README.md). If any of these steps filter this text or is unable to pair documents/sentences, those are not going to be written at the end. Check them all, not only crawl and output.

And please, don't mix topics in issues. As the initial Tensorflow issue is fixed, I am closing this issue and continue discussing this topic in #75.
