### ISSUE TITLE
Comments in Spanish

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#8]
Makes it hard to know what's going on, when there is documentation

**Comment by kpu** [comment]
Code in Spanish too: https://github.com/bitextor/bitextor/blob/master/bitextor-idx2ridx.py

**Comment by mespla** [comment]
I just translated all these comments and fixed some errors in documentation. I detected script "bitextor-ridx2filenames.py" that I am not sure what it does and I cannot document it. Probably @Lesbinary can add a comment to know what this script does.
