### ISSUE TITLE
tensorflow install on Ubuntu 16.04

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#83]
Following the README.md to install
1. pip3 install --user -r requirements.txt 
         - install ok (including tensorflow)
2. ./autogen.sh 
     configure: error: this package requires the following libraries for Python:
     - tensorflow:   Please, install tensorflow and try again: sudo pip install tensorflow
   It seems like tensorflow segfaults
        $ python3
        ...>>> import tensorflow
       Illegal instruction (core dumped)
Commenting out the tensorflow and keras checks in configure allows autogen.sh to run successfully.

is it necessary to have tensorflow & keras?

**Comment by hieuhoang** [comment]
The segfault only happens on some machines, prob 'cos of inconsistent installation which I can't change. But the question of whether we can get by without tensorflow & keras is still worth knowing

**Comment by lpla** [comment]
That `Illegal instruction (core dumped)` error could be fixed doing this: https://github.com/bitextor/bitextor#some-known-installation-issues

Also, `keras` (and depending `tensorflow`) are required if you are using features-based document aligner. If you are using translation-based document aligner, it is not required.

**Comment by hieuhoang** [comment]
installing tensorflow 1.5.0 doesn't fix it, I'm not gonna manually install tensorflow if my pipeline doesn't require it.
