### ISSUE TITLE
Issues with build dictionary

### ISSUE THREAD

**Issue by WPti** [bitextor/bitextor#84]
I seem to have issues running ./bitextor-builddics.sh whereas my command line is like 

./bitextor-builddics.sh [-t /home/tmp/]  en de /home/pathto/dev.lang1 /home/pathto/dev.lang2 /home/pathto/output

I had errors like:
......
./bitextor-builddics.sh: line 108: /home/pathto/output/: Is a directory
/home/pathto/dev.lang2: line 1: Wissen: command not found
./bitextor-builddics.sh: line 108: /tmp/tempcorpuspreproc.MalN1/corpus.tok./home/tmp]: No such file or directory

LOWERCASING THE CORPUS...
cat: /tmp/tempcorpuspreproc.MalN1/corpus.tok./home/tmp]: No such file or directory
./bitextor-builddics.sh: line 114: /tmp/tempcorpuspreproc.MalN1/corpus.tok.low./home/tmp]: No such file or directory
......
FILTERING OUT TOO LONG SENTENCES...
FORMATTING THE CORPUS FOR PROCESSING...
mv: cannot stat ‘/tmp/tempcorpuspreproc.MalN1/corpus.clean.[-t_corpus.clean./home/tmp].snt’: No such file or directory
mv: cannot stat ‘/tmp/tempcorpuspreproc.MalN1/corpus.clean./home/rmp]_corpus.clean.[-t.snt’: No such file or directory
mv: cannot stat ‘/tmp/tempcorpuspreproc.MalN1/corpus.clean.[-t.vcb’: No such file or directory
mv: cannot stat ‘/tmp/tempcorpuspreproc.MalN1/corpus.clean./home/tmp].vcb’: No such file or directory

It appears that the path is messed. Any idea?

Appreciate!

W

**Comment by lpla** [comment]
Try with this:

```
./bitextor-builddics.sh -t /home/tmp/ en de /home/pathto/dev.lang1 /home/pathto/dev.lang2 /home/pathto/output.dic
```

**Comment by WPti** [comment]
Using the suggested command I have got this assuming error:

USAGE: bitextor-builddics.sh [-t tmp-dir] SL TL SL_FILE TL_FILE DIC [ PREPROCESSED_CORPUS [PRODUCED_MODELS] ]
WHERE
   -t tmp-dir            alternative tmp directory (/tmp by default)
   SL                    source language code (two characters)
   TL                    target language code (two characters)
   SL_FILE               file containing the source language segments (can be gzipped)
   TL_FILE               file containing the target language segments (can be gzipped)
   DIC                   output dictionary
   WORDTOKENISERSL       script used to tokenise source language words
   WORDTOKENISERTL       script used to tokenise target language words
   PREPROCESSED_CORPUS   folder to store the resulting pre-processed files (tokenised, lowercased and leared). If no folder is specified, a temporal folder is created
   PRODUCED_MODELS       folder to store the resulting models obtained as a by-product of the dictionaries building. If no folder is specified, a temporal folder is created

**Comment by WPti** [comment]
I recon your code will not run on other version of Linux apart from Ubuntu ?

**Comment by WPti** [comment]
From the bash file bitextor-builddics.sh, how should I find the directory for the tokenizer? 

We need to specify this to run the tokenization.  It is unclear from documentation. 

Thanks!

**Comment by lpla** [comment]
Yes, you are right. I was looking at the old version of this code and the newest code doesn't have that part of help updated. Now it is mandatory to give to this script the path of SL and TL tokenizer (Moses tokenizer included in Bitextor should work to test it). If you are at the root of Bitextor code, just:

```
./bitextor-builddics.sh -t /home/tmp/ en de /home/pathto/dev.lang1 /home/pathto/dev.lang2 /home/pathto/output.dic "preprocess/moses/tokenizer/tokenizer.perl -l en" "preprocess/moses/tokenizer/tokenizer.perl -l de"
```

I am updating the help command now.

**Comment by WPti** [comment]
Appreciate for the quick response. Still having complaints from console:

getopt: invalid option -- 'l'
getopt: invalid option -- 'l'
The path specified for storing the preprocessed files for the corpus is not valid.

W

**Comment by lpla** [comment]
Oops, that's what happens when I didn't try it before commenting. I usually have an external script with all parameters for Moses tokenizer, so that's why `bash` is crashing when passing this as string.

If you don't know how to do this, try Moses tokenizer without language parameter:

```
./bitextor-builddics.sh -t /home/tmp/ en de /home/pathto/dev.lang1 /home/pathto/dev.lang2 /home/pathto/output.dic preprocess/moses/tokenizer/tokenizer.perl preprocess/moses/tokenizer/tokenizer.perl
```

If you want a better tokenization, my suggestion is to create a `.sh` file with the command you want to use, and then substitute the Moses tokenizer from previous command.

**Comment by WPti** [comment]
Sounds great. I changed the bash script at my local repo replacing paths with my environment. It works! I have looked at the dictionary and it appears only capturing pairs. Any n-gram implementation?

Appreciate!

**Comment by lpla** [comment]
We only generate dictionaries with pairs of 1-grams, as that is what we need in hunalign and dictionary based document alignment.
