### ISSUE TITLE
deduped_tmx error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#86]
Some language pairs are starting to finish now. yoohoo! I get this error, probably because you can't put all the domain names as a command line argument: 

Error in rule deduped_tmx:
    jobid: 0
    output: /home/s0565741/workspace/experiment/paracrawl/v3/ga-en/permanent/ga-en.deduped.tmx.xz

RuleException:
OSError in line 1369 of /mnt/magni0/hieu/workspace/github/paracrawl/bitextor.malign/snakemake/Snakefile:
[Errno 7] Argument list too long

**Comment by lpla** [comment]
Pull `bitextor-malign` branch and try again. It should work now for deduped TMX.

**Comment by hieuhoang** [comment]
excellent
