### ISSUE TITLE
Any interest in a Docker container-based build for this project?

### ISSUE THREAD

**Issue by lpmi-13** [bitextor/bitextor#87]
The build steps for this project seem complex, but predictable, and I wonder if it would be easier for researchers to not need to worry about java8/python3/tensorflow/etc?

**Comment by hieuhoang** [comment]
That would be fab! Git pull request if you do it

**Comment by hieuhoang** [comment]
Give me a shout if you need any advise

**Comment by lpla** [comment]
Any progress on this, @amirkamran ?

**Comment by lpmi-13** [comment]
I'm happy to see what I can put together, but do we have an idea of the bare minimum functionality that a "fully functioning" docker container would need to be able to replicate?

**Comment by hieuhoang** [comment]
I would say it has to be able to run 1 of the ??-en.yaml files in here to completion
   https://github.com/bitextor/bitextor/tree/master/snakemake/example/hieu
These are currently running on a cluster without docker

**Comment by lpla** [comment]
Docker [ready](https://github.com/bitextor/bitextor/blob/master/docs/README.md#docker-installation)!
```

docker pull paracrawl/bitextor

docker run -it paracrawl/bitextor
```
