### ISSUE TITLE
Simple test of installation

### ISSUE THREAD

**Issue by wwaites** [bitextor/bitextor#92]
What is the easiest way to test an installation of bitextor? A common convention is one of:

    make test
    python setup.py nosetests

This is important for CI (cf #91) and for checking dependency problems (cf #90)

**Comment by wwaites** [comment]
I must be blind. There is a `run-tests.sh`

**Comment by wwaites** [comment]
Re-opening because `run-tests.sh` fails with the error:

    RuleException in line 1031 of /projects/ParaCrawl/bitextor/snakemake/Snakefile:
NameError: The name 'WORDTOK1' is unknown in this context. Please make sure that you defined that variable. Also note that braces not used for variable access have to be escaped by repeating them, i.e. {{print $1}}

Following this back, this block in the Snakefile:

    #Tokenisers
    if "LANG1Tokenizer" in config:
      WORDTOK1=config["LANG1Tokenizer"]

suggests that there is no `LANG1Tokenizer` in the config. At this stage I'm not certain where the config that it is looking for comes from.

**Comment by wwaites** [comment]
I would also suggest that the `run-tests.sh` should not be creating directories under $HOME. This is surprising and potentially dangerous if I happen to already have a directories called `reports` or `permanent` there, or insufficient disc space, etc.

**Comment by hieuhoang** [comment]
Thats true, you need to set lang1tokenizer. The code was changed to not set a default as discussed in the last meeting

**Comment by lpla** [comment]
I still need to address the $HOME directory issue in test config files. I will move those affected parameters to `run-tests.sh` (as `--config` parameters instead) to get modified by Bash $WORK variable. Let me some time to change it and test it.

**Comment by lpla** [comment]
Please, @wwaites, pull latest changes and try again. If you don't want to run all tests (en-ru run can take more than an hour in a desktop machine), comment some `snakemake` calls from `run-tests.sh`. "en-el" pair is the smallest test.
