### ISSUE TITLE
Installation with conda

### ISSUE THREAD

**Issue by wwaites** [bitextor/bitextor#93]
Anaconda/miniconda is useful for self-contained installations of software, particularly python but also other languages and binaries. For example,

    conda install tensorflow-gpu

installs tensorflow as well as all dependencies, including CUDA libraries and so forth.

It would be ideal to be able to do,

    conda create -n bitextor python=3
    conda activate bitextor
    conda install bitextor

and get a complete, working installation. For some environments, such as the HPC systems, this may be more convenient than the approach in #87 as Docker is unlikely to be available. At the same time, it supports #87 because it gives a very straightforward way of creating such a Docker container.

**Comment by mzeidhassan** [comment]
Sorry to jump in. Any update on this one?

**Comment by wwaites** [comment]
Sort of. bitextor is not installable in the usual way with `pip install` or `conda install`. However it will run in a conda environment. This basically means creating the environment and then checking out the source repository and going through the documented installation steps. I think that development of bitextor is very active but it's a good idea to think about freezing release versions at points where it makes sense.

**Comment by cgr71ii** [comment]
A conda build has been released. In order to install the conda version, use `conda install -c bitextor bitextor=8=80_g1ee4f1bb`. If any problem appears, please, open an issue (it is WIP).

**Comment by lpla** [comment]
Previous conda package was based on a development branch. Now that latest Bitextor code (for the near v8.0 release) reached master branch, we built a conda package using that code. Just run `conda install -c bitextor bitextor` , as noted in the documentation. Conda will only store release versions, not nightlies. Closing issue.
