### ISSUE TITLE
rule sents for large language pair 

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#98]
ok, getting to the business end of the pipeline now, the end is in sight!

when running on fr-en, I get the error below. If you can think of a better way to write the rule, otherwise I'll just hack a script to do it

rule sents:
    input: /home/s0565741/workspace/experiment/paracrawl/v3/fr-en/transient/centralasia-travel/bleualign.elrc.xz, /home/s0565741/workspace/experiment/paracrawl/v3/fr-en/.....(huge list)
...
sbatch: error: Batch job submission failed: Pathname of a file, directory or other parameter too long
Error submitting jobscript (exit code 1):

**Comment by lpla** [comment]
Can you attach the full list? Looks like one domain has a very long name.

**Comment by hieuhoang** [comment]
i think it's the list that too long. Links directory with hosts.gz and nohup.out
   http://statmt.org/hieu/paracrawl/rule.sent/
Dont worry too much about this error, I've hacked a script to do it
   https://github.com/bitextor/bitextor/commit/0ae06577deb96b09504ae800882138512773a55e
The TMX error I can't solve

**Comment by lpla** [comment]
Ok, I will look at the TMX error first. Also, regarding this one, maybe adding some configuration to the `slurm` config files could fix it: https://bugs.schedmd.com/show_bug.cgi?id=2198#c1

**Comment by hieuhoang** [comment]
you're right, it is a slurm issue. Solution - don't use slurm for the last rules!
