### ISSUE TITLE
rule deduped_tmx: error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#99]
input file: http://statmt.org/hieu/paracrawl/ro-en.sent.xz

error:
rule deduped_tmx:
    input: /home/s0565741/workspace/experiment/paracrawl/v3/ro-en/permanent/ro-en.sent.xz
    output: /home/s0565741/workspace/experiment/paracrawl/v3/ro-en/permanent/ro-en.deduped.tmx.xz
    jobid: 0
    wildcards: l2=en, l1=ro

Traceback (most recent call last):
  File "/home/s0565741/workspace/github/paracrawl/bitextor.malign/bitextor-buildTMX-dedup.py", line 140, in <module>
    print_tu(prevfieldsdict, urls1, urls2, idnum)
  File "/home/s0565741/workspace/github/paracrawl/bitextor.malign/bitextor-buildTMX-dedup.py", line 47, in print_tu
    if "numTokensSL" in fieldsdict and fieldsdict["numTokensSL"] != "" and int(fieldsdict["numTokensSL"]) < int(
ValueError: invalid literal for int() with base 10: '1.0'
[Fri May 17 20:56:42 2019]
Error in rule deduped_tmx:
    jobid: 0
    output: /home/s0565741/workspace/experiment/paracrawl/v3/ro-en/permanent/ro-en.deduped.tmx.xz

RuleException:
CalledProcessError in line 1414 of /mnt/magni0/hieu/workspace/github/paracrawl/bitextor.malign/snakemake/Snakefile:
Command ' sync; set -euo pipefail;  xzcat -T 0 -f /home/s0565741/workspace/experiment/paracrawl/v3/ro-en/permanent/ro-en.sent.xz | LC_ALL=C sort -t$'	' -k3,4 -T /raid0/tmp --compress-program=gzip |  /home/s0565741/workspace/github/paracrawl/bitextor.malign/bitextor-buildTMX-dedup.py --lang1 ro --lang2 en -c url1,url2,seg1,seg2,hunalign,lengthratio,numTokensSL,numTokensTL | xz -T 0 > /home/s0565741/workspace/experiment/paracrawl/v3/ro-en/permanent/ro-en.deduped.tmx.xz ' returned non-zero exit status 1
  File "/mnt/magni0/hieu/workspace/github/paracrawl/bitextor.malign/snakemake/Snakefile", line 1414, in __rule_deduped_tmx
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job deduped_tmx since they might be corrupted:
/home/s0565741/workspace/experiment/paracrawl/v3/ro-en/permanent/ro-en.deduped.tmx.xz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by lpla** [comment]
The specific error is: `ValueError: invalid literal for int() with base 10: '1.0'`

This cannot happen if the input columns are well defined. After looking into the attached input file, I see these columns: 

url1,url2,seg1,seg2,hunalign,**bicleaner**,lengthratio,numTokensSL,numTokensTL

I marked BICLEANER_SCORE because I don't see it in the Command you used:

sync; set -euo pipefail; xzcat -T 0 -f /home/s0565741/workspace/experiment/paracrawl/v3/ro-en/permanent/ro-en.sent.xz | LC_ALL=C sort -t$'	' -k3,4 -T /raid0/tmp --compress-program=gzip | /home/s0565741/workspace/github/paracrawl/bitextor.malign/bitextor-buildTMX-dedup.py --lang1 ro --lang2 en -c **url1,url2,seg1,seg2,hunalign,lengthratio,numTokensSL,numTokensTL** | xz -T 0 > /home/s0565741/workspace/experiment/paracrawl/v3/ro-en/permanent/ro-en.deduped.tmx.xz


So, `bitextor-buildTMX-dedup.py` is matching `numTokensSL` (integer) with the `bicleaner` column from ro-en.sent.xz (float).

I think you only need to revise Snakemake config file and add Bicleaner option.

**Comment by hieuhoang** [comment]
ah I see. I hadn't been running bicleaner 'cos of some errors. Might as well start debugging that now

So running it with the bicleaner option, I get the follow error. The command I ran is
   snakemake --snakefile ../../Snakefile -j 1  --latency-wait 10 --configfile config.ro-en.yam
The bicleaner models were copied from somewhere on the 3rd April. Config file:
   http://statmt.org/hieu/paracrawl/config.ro-en.yaml

Error:
   NumPy release.
  from numpy.core.umath_tests import inner1d
Traceback (most recent call last):
  File "kenlm.pyx", line 114, in kenlm.Model.__init__ (python/kenlm.cpp:2132)
RuntimeError: lm/model.cc:49 in void lm::ngram::detail::{anonymous}::CheckCounts(const std::vector<long unsigned int>&) threw FormatLoadException because `counts.size() > 6'.
This model has order 7 but KenLM was compiled to support up to 6.  If your build system supports changing KENLM_MAX_ORDER, change it there and recompile.  In the KenLM tarball or Moses, use e.g. `bjam --max-kenlm-order=6 -a'.  Otherwise, edit lm/max_order.hh.

The above exception was the direct cause of the following exception:

**Comment by lpla** [comment]
Looks like you need to compile KenLM to support 7-grams, as Bicleaner needs it: https://github.com/bitextor/bicleaner#installation--requirements

**Comment by hieuhoang** [comment]
which bicleaner does Snakemake use? The submodule in bitextor? The pip installed version (there's no mention in it requirements.txt)? Or should I manually pip3 install it?

**Comment by lpla** [comment]
The submodule one, for now.

**Comment by hieuhoang** [comment]
so I should make the changes in the submoduke version and recompile?

**Comment by hieuhoang** [comment]
there doesn't seem to be kenlm in the submodule

**Comment by lpla** [comment]
Nope, you need to recompile `kenlm`, not `bicleaner`. You can do it manually:

`git clone https://github.com/kpu/kenlm`
In kenlm/setup.py, replace

`ARGS = ['-O3', '-DNDEBUG', '-DKENLM_MAX_ORDER=6', '-std=c++11'] with ARGS = ['-O3', '-DNDEBUG', '-DKENLM_MAX_ORDER=7', '-std=c++11']`

```
python kenlm/setup.py install
cd kenlm/build
cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=/your/prefix/path
make -j all install
```


Or do this automatically with pip:
`pip3 install https://github.com/vitaka/kenlm/archive/master.zip`

**Comment by hieuhoang** [comment]
Still same error. Prob best I leave it 'til the bicleaner installation is more consistent. 

It's the last step so I can rerun the pipeline for all languages once it's done

**Comment by lpla** [comment]
Ok. In case you want to fix initial issue without running bicleaner or changing the config file, just create the same input file without bicleaner column:

`xzcat ro-en.sent.xz | cut -f 1,2,3,4,5,7,8,9 | xz > ro-en.sent.without-bicleaner.xz`

**Comment by hieuhoang** [comment]
I can wait, I prefer to have the real bicleaner scores. 

This will cause future re-run to think everything is complete

**Comment by lpla** [comment]
Well, in this case, I am closing this issue. If you have any problem with bicleaner installation, just let me know.

**Comment by hieuhoang** [comment]
ok. I'll bug you in a few weeks about it.

**Comment by mbanon** [comment]
Did someone say "bicleaner"? :ear:
It seems like you are installing KenLM in a given Python environment, but running the whole thing from another one?

**Comment by hieuhoang** [comment]
aye, it sounds like bicleaner installlation is a bit mixed up in bitextor. I'm not sure what it's running and what's installed

Should I uninstall bicleaner totally from the virtual env and run whatever is in bitextor?

**Comment by hieuhoang** [comment]
and kenlm too

**Comment by mbanon** [comment]
ummm maybe, at least just to see what happens.
TBH, I am not 100% sure on how is bicleaner integrated into snakemake/bitextor, so @lpla probably knows best.

**Comment by hieuhoang** [comment]
looks like you hit the right spot. I unstalled then reinstalled kenlm from https://github.com/vitaka/kenlm/archive/master.zip

Also deleted all previous bicleaner output. It worked on a small subset of the domains. Trying it on all ro-en now

**Comment by lpla** [comment]
KenLM needs to be clean installed (uninstall and install in case it was already compiled with other n-gram limit) as it is a bicleaner dependency. Bitextor uses bicleaner without installing it, for now. That is calling to the scripts in the submodule folder, not to the executables in path.

**Comment by lpla** [comment]
Also, if this is working now, please close this issue.

**Comment by hieuhoang** [comment]
Yep, clean install of kenlm is the solution
